const $=s=>document.querySelector(s);
const api=(url,opt={})=>window.staticApi(url,opt);
const DAYS=['LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO'];
let current=null,editing=null,currentMonthly=null,editingMonthly=null,restoringMonthlyFilters=false,monthlyFilterState={errorsOnly:false,infoOnly:false,code:'',allUnits:true,units:[]};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const duration=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const STATUS_LABELS={UPLOADED:'Archivo subido',PARSED:'Archivo procesado',WITH_ERRORS:'Con errores',READY_FOR_REVIEW:'Listo para revisión',VALIDATED:'Validada',CORRECTED:'Corregida',VALIDATED_AFTER_CORRECTION:'Validada después de corrección',REJECTED:'Rechazada'};
const RULE_LABELS={MAX_WEEKLY_ORDINARY_HOURS:'Máximo de jornada semanal',MAX_WEEKLY_NIGHT_SELLER_HOURS:'Máximo semanal de Vendedor Nocturno',MAX_DAILY_ORDINARY_HOURS:'Máximo de jornada diaria',CONTRACT_WEEKLY_HOURS:'Jornada semanal contractual',EMPLOYMENT_PERIOD:'Período de contratación',EMPLOYMENT_START_DATE:'Fecha de inicio de contratación',EMPLOYMENT_END_DATE:'Fecha de término de contratación',EMPLOYEE_ACTIVE:'Estado activo del colaborador',EMPLOYEE_NOT_FOUND:'Colaborador no encontrado',EMPLOYEE_FROM_IMPORT:'Colaborador conservado desde el Excel',INCOMPLETE_CONTRACT:'Información contractual incompleta',STORE_AUTHORIZATION:'Autorización para trabajar en el local',BREAK_REQUIRED:'Colación requerida',MAX_WORK_BEFORE_BREAK_MINUTES:'Supera las 5 horas para colación',SPLIT_SHIFT_ALLOWED:'Autorización de jornada dividida',MIN_REST_BETWEEN_WORK_DAYS:'Descanso mínimo entre jornadas menor a 12 horas',MAX_CONSECUTIVE_WORK_DAYS:'Máximo de días laborales consecutivos',MAX_CONSECUTIVE_WEEKS_SAME_START:'Máximo de semanas con la misma hora de inicio',MAX_CONSECUTIVE_WEEKS_SAME_END:'Máximo de semanas con la misma hora de término',QF_COVERAGE:'Cobertura de químico farmacéutico',INVALID_15_MINUTE_INCREMENT:'Horario fuera de intervalos de 15 minutos',INVALID_WORK_INTERVAL:'Formato de horario inválido',INVALID_TIME_ORDER:'Orden de horas inválido',OVERLAPPING_WORK_INTERVALS:'Turnos superpuestos',BREAK_OUTSIDE_WORK:'Colación fuera de la jornada',EMPTY_DAY:'Día sin información'};
RULE_LABELS.MAX_CONSECUTIVE_WEEKS_SAME_START_OR_END_TIME='Rotación de horario requerida';
RULE_LABELS.MAX_CONSECUTIVE_WEEKS_SAME_START_TIME='Rotación de horario inicio requerida';
RULE_LABELS.MAX_CONSECUTIVE_WEEKS_SAME_END_TIME='Rotación de horario cierre requerida';
const statusLabel=value=>STATUS_LABELS[value]||value,ruleLabel=value=>RULE_LABELS[value]||value.replaceAll('_',' ').toLowerCase();

function render(data){
 current=data; $('#review').classList.remove('hidden');
 $('#filename').textContent=data.original_filename;
 $('#period').textContent=`Semana ${data.week_start||'sin fecha'} al ${data.week_end||'sin fecha'} · ${statusLabel(data.status)}`;
 const structural=data.issues||[],legal=data.legalValidation;
 const errors=structural.filter(x=>x.severity==='ERROR').length+(legal?.blockingErrors||0);
 const warnings=structural.filter(x=>x.severity==='WARNING').length+(legal?.warnings||0);
 const total=data.rows.length*7,ok=total-structural.filter(x=>x.day_id).length;
 $('#stats').innerHTML=[['Colaboradores',data.rows.length],['Días procesados',total],['Correctos',ok],['Advertencias',warnings],['Errores',errors],['Legalidades',legal?.results?.length||0]].map(x=>`<div class="stat"><b>${x[1]}</b>${x[0]}</div>`).join('');
 $('#statusBanner').innerHTML=errors
  ?`<div class="banner error"><b>${errors} error(es) bloqueantes requieren revisión.</b> Haz clic en el indicador rojo de legalidades para ver el detalle.</div>`
  :`<div class="banner ok"><b>Sin incumplimientos bloqueantes detectados.</b> La planificación puede validarse según las reglas configuradas.</div>`;
 $('#rows').innerHTML=data.rows.map(r=>{
  const le=legal?.employees?.find(x=>x.rowId===r.id),leBad=(le?.errors||0)>0;
  const rowBad=r.issues.length||Object.values(r.days).some(d=>d.issues.length)||leBad;
  const cells=DAYS.map(n=>{const d=r.days[n],bad=d.issues.length;return`<td class="day ${bad?'bad':''}" data-day="${d.id}" data-name="${n}">${escape(d.corrected_value??d.original_value)||'<em>SIN INFORMACIÓN</em>'}${bad?`<small>ERROR · ${escape(d.issues[0].message)}</small>`:''}</td>`}).join('');
  const legalLabel=le?le.errors?`❌ ${le.errors}`:le.warnings?`⚠ ${le.warnings}`:'✅ 0':'—';
  return`<tr data-row="${r.id}"><td><b>${escape(r.employee_name_original)}</b></td><td>${escape(r.rut_original)}</td>${cells}<td><b>${le?duration(le.weeklyWorkedMinutes):'—'}</b></td><td><button class="pill legalTrigger ${leBad?'bad':''}" data-legal-row="${r.id}">${legalLabel}</button></td><td><span class="pill ${rowBad?'bad':''}">${rowBad?'Error':'Correcto'}</span></td></tr>`;
 }).join('');
 $('#confirm').classList.toggle('hidden',data.status!=='PARSED');
 $('#export').classList.toggle('hidden',!['VALIDATED','VALIDATED_AFTER_CORRECTION'].includes(data.status));
 document.querySelectorAll('.day').forEach(x=>x.onclick=()=>openEditor(x.dataset.day,x.dataset.name));
 document.querySelectorAll('.legalTrigger').forEach(x=>x.onclick=()=>openLegal(x.dataset.legalRow));
}

function openLegal(rowId){
 const row=current.rows.find(x=>x.id===rowId),summary=current.legalValidation?.employees?.find(x=>x.rowId===rowId),results=summary?.results||[];
 $('#legalTitle').textContent=`${row.employee_name_original} · ${row.rut_original}`;
 $('#legalList').innerHTML=results.length?results.map(x=>`<article class="legalItem ${x.severity.toLowerCase()}"><h3>${x.severity==='ERROR'?'❌':x.severity==='WARNING'?'⚠️':'ℹ️'} ${escape(ruleLabel(x.ruleCode))}</h3><p>${escape(x.message)}</p><div class="legalMeta"><span>Severidad: ${x.severity==='ERROR'?'Error':x.severity==='WARNING'?'Advertencia':'Información'}</span><span>${x.blocking?'Bloqueante':'No bloqueante'}</span>${x.date?`<span>Fecha: ${escape(x.date)}</span>`:''}${x.actualValue!=null?`<span>Detectado: ${escape(x.actualValue)}</span>`:''}${x.expectedValue!=null?`<span>Permitido: ${escape(x.expectedValue)}</span>`:''}</div></article>`).join(''):'<div class="banner ok">✅ Este colaborador no presenta incumplimientos detectados según las reglas configuradas.</div>';
 $('#legalDialog').showModal();
}
$('#closeLegal').onclick=()=>$('#legalDialog').close();
$('#closeLegalBottom').onclick=()=>$('#legalDialog').close();

async function upload(file){
 $('#uploadError').classList.add('hidden');const fd=new FormData();fd.append('file',file);
 const response=await api('/api/v1/planning-imports/upload',{method:'POST',body:fd}),data=await response.json();
 if(!response.ok){$('#uploadError').textContent=data.message;$('#uploadError').classList.remove('hidden')}else render(data);
}
$('#file').onchange=e=>e.target.files[0]&&upload(e.target.files[0]);
const drop=$('#drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');e.dataTransfer.files[0]&&upload(e.dataTransfer.files[0])};
$('#confirm').onclick=async()=>render(await(await api(`/api/v1/planning-imports/${current.id}/confirm`,{method:'POST'})).json());
$('#validate').onclick=async()=>{const response=await api(`/api/v1/planning-imports/${current.id}/validate`,{method:'POST'});render(await response.json())};
$('#export').onclick=async()=>{const x=await(await api(`/api/v1/planning-imports/${current.id}/export`,{method:'POST'})).json();location.href=x.url};

function addTurn(start='',end=''){
 if(document.querySelectorAll('.turn').length>=2)return;const el=document.createElement('div');el.className='turn';
 el.innerHTML=`<label>Inicio<input type="time" step="900" class="start" value="${start}"></label><label>Fin<input type="time" step="900" class="end" value="${end}"></label><button type="button" class="remove">×</button>`;
 el.querySelector('.remove').onclick=()=>el.remove();el.querySelectorAll('input').forEach(x=>x.onchange=()=>suggestBreak(true));$('#turns').append(el);
}
const toMinutes=t=>{const[h,m]=t.split(':').map(Number);return h*60+m},toTime=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const endMinutes=(start,end)=>toMinutes(end)+(((toMinutes(end)===0&&toMinutes(start)>0)||(toMinutes(start)>=18*60&&toMinutes(end)<=12*60))?1440:0);
function clearBreak(){$('#breakStart').value='';$('#breakEnd').value=''}
function suggestBreak(force=false){const first=$('.turn'),start=first?.querySelector('.start').value,end=first?.querySelector('.end').value;if(!start||!end)return;const shiftEnd=endMinutes(start,end),shiftMinutes=shiftEnd-toMinutes(start);if(shiftMinutes<=300){clearBreak();return}const existing=$('#breakStart').value,existingMinute=existing?(toMinutes(existing)<toMinutes(start)?toMinutes(existing)+1440:toMinutes(existing)):0,invalid=existing&&(existingMinute<toMinutes(start)||existingMinute>=shiftEnd||existingMinute-toMinutes(start)>300);if(!force&&existing&&!invalid)return;let suggested=Math.floor((toMinutes(start)+240)/60)*60;suggested=Math.min(suggested,toMinutes(start)+300,shiftEnd-30);$('#breakStart').value=toTime(suggested);$('#breakEnd').value=toTime(Math.min(suggested+60,shiftEnd))}
function openEditor(id,name){editing=Object.values(current.rows.flatMap(r=>Object.values(r.days))).find(d=>d.id===id);$('#editTitle').textContent=name;$('#dayType').value=['FREE','VACATION','FLEX'].includes(editing.day_type)?editing.day_type:'WORK';$('#turns').innerHTML='';editing.intervals.filter(x=>x.type==='WORK').forEach(x=>addTurn(x.start,x.end));if(!$('#turns').children.length)addTurn();const b=editing.intervals.find(x=>x.type==='BREAK');$('#breakStart').value=b?.start||'';$('#breakEnd').value=b?.end||'';suggestBreak(false);toggleWork();$('#editor').showModal()}
function openMonthlyEditor(fileIndex,sheetName,rowNumber,columnNumber,name){const file=currentMonthly.files[fileIndex],sheet=file.sheets.find(x=>x.sheet===sheetName),row=sheet.rows.find(x=>x.rowNumber===rowNumber),day=row.days.find(x=>x.columnNumber===columnNumber);editingMonthly={fileIndex,sheetName,rowNumber,columnNumber,day};editing=null;$('#editTitle').textContent=`${name} · ${day.date}`;$('#dayType').value=['FREE','VACATION','FLEX'].includes(day.dayType)?day.dayType:'WORK';$('#turns').innerHTML='';day.intervals.filter(x=>x.type==='WORK').forEach(x=>addTurn(x.start,x.end));if(!$('#turns').children.length)addTurn();const b=day.intervals.find(x=>x.type==='BREAK');$('#breakStart').value=b?.start||'';$('#breakEnd').value=b?.end||'';suggestBreak(false);toggleWork();$('#editor').showModal()}
function toggleWork(){$('#workFields').classList.toggle('hidden',$('#dayType').value!=='WORK')}
$('#dayType').onchange=toggleWork;$('#addTurn').onclick=()=>addTurn();
for(const[value,label]of[['ABSENCE','Ausencia'],['UNWAIVABLE_HOLIDAY','Feriado irrenunciable'],['ADDITIONAL_SUNDAY','DA · Domingo adicional']])if(!$('#dayType').querySelector(`option[value="${value}"]`))$('#dayType').insertAdjacentHTML('beforeend',`<option value="${value}">${label}</option>`);
$('#removeBreak').onclick=clearBreak;
document.addEventListener('mouseover',event=>{const cell=event.target.closest?.('.monthlyDay.info');if(!cell||cell.dataset.tooltip)return;const message=/D[ií]a\s+Flex/i.test(cell.textContent)?'Día Flex informado: corresponde a un día libre o sin jornada laboral, no computa horas y no es un error.':/(Vac\.?|Vacaciones)/i.test(cell.textContent)?'Vacaciones informadas: este día no computa horas trabajadas y no corresponde a un error.':'Colación iniciada dentro de las primeras 5 horas de la jornada: condición permitida e informativa.';cell.dataset.tooltip=message;cell.title=message});
let selectedMonthly=[];
$('#monthlyFiles').onchange=e=>{selectedMonthly=[...e.target.files];$('#validateMonthly').disabled=!selectedMonthly.length;$('#monthlySelection').textContent=selectedMonthly.length?`${selectedMonthly.length} archivo(s): ${selectedMonthly.map(x=>x.name).join(', ')}`:''};
$('#validateMonthly').onclick=async()=>{const button=$('#validateMonthly');button.disabled=true;button.textContent='Validando…';const form=new FormData(),fileDate=file=>file.name.match(/(\d{2})_(\d{2})_(\d{4})/)?.slice(1).reverse().join('-')??file.name;[...selectedMonthly].sort((a,b)=>fileDate(a).localeCompare(fileDate(b))).forEach(x=>form.append('files',x));try{const response=await api('/api/v1/monthly-validations/upload',{method:'POST',body:form}),data=await response.json();if(!response.ok)throw new Error(data.message);renderMonthly(data)}catch(e){$('#monthlyResult').classList.remove('hidden');$('#monthlyResult').innerHTML=`<div class="banner error">${escape(e.message)}</div>`}finally{button.disabled=false;button.textContent='Validar archivos seleccionados'}};
function renderMonthly(data){
 rememberMonthlyFilters();currentMonthly=data;const s=data.summary,units=[...new Set(data.files.flatMap(f=>f.sheets.flatMap(w=>w.rows.map(r=>r.workUnit))))].sort();
 $('#monthlyResult').classList.remove('hidden');
 $('#monthlyResult').innerHTML=`<div class="banner ${s.blockingErrors?'error':'ok'}"><b>${s.blockingErrors?'La información mensual presenta incumplimientos. Corrige las celdas marcadas.':'Información mensual validada sin incumplimientos bloqueantes.'}</b></div>
 <div class="monthlySummary">${[['Archivos',s.files],['Locales',s.stores],['Colaboradores',s.employees],['Errores',s.errors],['Advertencias',s.warnings]].map(x=>`<div class="stat"><b>${x[1]}</b>${x[0]}</div>`).join('')}</div>
 <div class="monthlyFilters"><label>Unidad de trabajo<select id="unitFilter"><option value="">Todas</option>${units.map(x=>`<option value="${escape(x)}">${escape(x)}</option>`).join('')}</select></label><label class="checkFilter"><input type="checkbox" id="errorsOnly"> Ver solo líneas con error</label></div>
 ${data.files.map((f,fi)=>`<section class="monthlyFile"><div class="monthlyHead"><div><h3>${escape(f.store||'Local no informado')}</h3><p>${escape(f.filename)} · ${f.sheets.length} semanas · ${f.employees.length} colaboradores</p></div><a class="button secondary" href="/api/v1/monthly-validations/${data.id}/files/${fi}/export">Descargar Excel corregido</a></div>
 ${f.sheets.map(sheet=>`<div class="monthlySheet"><h4>${escape(sheet.sheet)} · ${sheet.weekStart} al ${sheet.weekEnd}</h4><div class="tableWrap"><table class="monthlyTable"><thead><tr><th>Trabajador</th><th>Código</th><th>Contrato</th><th>Local</th><th>Unidad de trabajo</th>${sheet.dates.map(x=>`<th>${escape(x)}</th>`).join('')}<th>Total horas semana</th></tr></thead><tbody>
 ${sheet.rows.map(row=>{const rowIssues=data.results.filter(x=>x.metadata?.file===f.filename&&(x.metadata?.rowId===row.key||x.metadata?.rut===row.code)&&(x.date==null||(x.date>=sheet.weekStart&&x.date<=sheet.weekEnd)));return`<tr class="monthlyEmployeeRow" data-unit="${escape(row.workUnit)}" data-error="${rowIssues.some(x=>x.severity==='ERROR')?'1':'0'}"><td><b>${escape(row.name)}</b></td><td>${escape(row.code)}</td><td>${escape(row.contract)}</td><td>${escape(row.store)}</td><td>${escape(row.workUnit)}</td>${row.days.map(day=>{const issues=rowIssues.filter(x=>x.date===day.date),vac=day.dayType==='VACATION',work=day.intervals.find(x=>x.type==='WORK'),br=day.intervals.find(x=>x.type==='BREAK'),early=work&&br&&(toMinutes(br.start)-toMinutes(work.start)<=300);return`<td class="monthlyDay ${issues.some(x=>x.severity==='ERROR')?'bad':vac||early?'info':''}" data-monthly="1" data-file="${fi}" data-sheet="${escape(sheet.sheet)}" data-row="${row.rowNumber}" data-column="${day.columnNumber}" data-name="${escape(row.name)}">${escape(day.correctedValue??day.originalValue)||'<em>Sin información</em>'}${vac?'<small>Vacaciones</small>':''}${issues.length?`<small>${issues.map(x=>escape(ruleLabel(x.ruleCode))).join('<br>')}</small>`:''}</td>`}).join('')}<td><b>${row.showWeeklyHours?duration(row.workedMinutes):'—'}</b></td></tr>`}).join('')}</tbody></table></div></div>`).join('')}</section>`).join('')}`;
 document.querySelectorAll('[data-monthly]').forEach(cell=>cell.onclick=()=>openMonthlyEditor(Number(cell.dataset.file),cell.dataset.sheet,Number(cell.dataset.row),Number(cell.dataset.column),cell.dataset.name));$('#unitFilter').onchange=applyMonthlyFilters;$('#errorsOnly').onchange=applyMonthlyFilters;
}
async function downloadMonthly(event){event.preventDefault();if(currentMonthly?.summary?.blockingErrors){alert(`No se puede descargar el Excel corregido. Todavía quedan ${currentMonthly.summary.blockingErrors} error(es) bloqueantes por corregir.`);return false}const match=event.currentTarget.href.match(/files\/(\d+)\/export/);try{await window.downloadStaticMonthly(Number(match?.[1]??0))}catch(error){alert(error.message)}return false}
const unitCategory=value=>/^\s*Volantes/i.test(value)||/\/\s*Volantes/i.test(value)?'VOLANTES':/Vendedor\s+Noct\.?/i.test(value)?'NOCTURNO':/qu[ií]mico/i.test(value)?'QUIMICO':/operaciones/i.test(value)?'OPERACIONES':/vendedor/i.test(value)?'VENDEDOR':'OTRA';
function rememberMonthlyFilters(){if(restoringMonthlyFilters||!currentMonthly)return;monthlyFilterState={errorsOnly:!!$('#errorsOnly')?.checked,infoOnly:!!$('#infoOnly')?.checked,code:$('#codeFilter')?.value??'',allUnits:!!$('#unitAll')?.checked,units:[...document.querySelectorAll('.unitOption:checked')].map(x=>x.value)}}
function restoreMonthlyFilters(){if(!$('#unitCategoryFilter'))return;restoringMonthlyFilters=true;$('#errorsOnly').checked=monthlyFilterState.errorsOnly;if($('#infoOnly'))$('#infoOnly').checked=monthlyFilterState.infoOnly;if($('#codeFilter'))$('#codeFilter').value=monthlyFilterState.code;document.querySelectorAll('.unitOption').forEach(option=>option.checked=monthlyFilterState.units.includes(option.value));$('#unitAll').checked=monthlyFilterState.allUnits&&!monthlyFilterState.units.length;applyMonthlyFilters();restoringMonthlyFilters=false}
function applyMonthlyFilters(){rememberMonthlyFilters();const selected=[...document.querySelectorAll('.unitOption:checked')].map(x=>x.value),all=$('#unitAll')?.checked||!selected.length,errorsOnly=$('#errorsOnly')?.checked,infoOnly=$('#infoOnly')?.checked,code=($('#codeFilter')?.value??'').trim().toLowerCase();document.querySelectorAll('.monthlyEmployeeRow').forEach(row=>{const unitVisible=selected.includes(row.dataset.category)||(all&&row.dataset.category!=='VOLANTES'),codeVisible=!code||(row.dataset.code??'').toLowerCase().includes(code);row.classList.toggle('hidden',!unitVisible||!codeVisible||(errorsOnly&&row.dataset.error!=='1')||(infoOnly&&row.dataset.info!=='1'))})}
function enhanceMonthlyFilters(){const select=$('#unitFilter');if(!select||$('#unitCategoryFilter'))return;const rows=[...document.querySelectorAll('.monthlyEmployeeRow')],available=new Set(),codes=new Set();for(const row of rows){row.dataset.category=unitCategory(row.dataset.unit);if(row.dataset.category!=='OTRA')available.add(row.dataset.category);if(row.dataset.code)codes.add(row.dataset.code);row.dataset.info=row.querySelector('.monthlyDay.info')?'1':'0'}const labels={VENDEDOR:'Vendedor',NOCTURNO:'Vendedor Nocturno',OPERACIONES:'Operaciones',QUIMICO:'Químico Farmacéutico',VOLANTES:'Volantes'},holder=select.closest('label');holder.innerHTML=`<span>Unidades de trabajo</span><div id="unitCategoryFilter" class="unitChoices"><label><input type="checkbox" id="unitAll" checked> Todas excepto Volantes</label>${[...available].map(x=>`<label><input type="checkbox" class="unitOption" value="${x}"> ${labels[x]}</label>`).join('')}</div>`;const filters=holder.closest('.monthlyFilters');filters.insertAdjacentHTML('beforeend',`<label class="codeFilterLabel"><span>Código</span><input id="codeFilter" list="monthlyCodes" autocomplete="off" placeholder="Filtrar por código"><datalist id="monthlyCodes">${[...codes].sort().map(code=>`<option value="${escape(code)}"></option>`).join('')}</datalist></label><label class="checkFilter"><input type="checkbox" id="infoOnly"> Ver solo líneas informativas</label>`);$('#unitAll').onchange=e=>{if(e.target.checked)document.querySelectorAll('.unitOption').forEach(x=>x.checked=false);applyMonthlyFilters()};document.querySelectorAll('.unitOption').forEach(x=>x.onchange=()=>{const selected=document.querySelectorAll('.unitOption:checked').length;$('#unitAll').checked=!selected;applyMonthlyFilters()});$('#errorsOnly').onchange=applyMonthlyFilters;$('#infoOnly').onchange=applyMonthlyFilters;$('#codeFilter').oninput=applyMonthlyFilters;applyMonthlyFilters()}
function enhanceWeeklyTotals(){document.querySelectorAll('.monthlyEmployeeRow').forEach(row=>{const total=row.lastElementChild;if(total.querySelector('.weeklyStatus'))return;const markers=[...row.querySelectorAll('.monthlyDay small')],nightMarker=markers.find(x=>x.textContent.includes('Vendedor Nocturno')),marker=nightMarker||markers.find(x=>x.textContent.includes('Máximo de jornada semanal')),limit=row.dataset.category==='NOCTURNO'?2400:2520,limitText=duration(limit),match=total.textContent.trim().match(/^(\d{2}):(\d{2})/);if(!match||total.textContent.includes('—'))return;const weekly=Number(match[1])*60+Number(match[2]);if(marker||weekly>limit){total.classList.add('weeklyTotalError');total.insertAdjacentHTML('beforeend',`<span class="weeklyStatus errorStatus"><span class="weeklyFace sadFace"></span><small>Supera el máximo de ${limitText}</small></span>`);const day=marker?.closest('.monthlyDay');if(day)day.title=`Este turno hace que el acumulado semanal supere las ${limitText} horas.`;return}if(weekly<limit){total.classList.add('weeklyTotalUnder');total.insertAdjacentHTML('beforeend',`<span class="weeklyStatus underStatus"><span class="weeklyFace seriousFace"></span><small>Por debajo de ${limitText}</small></span>`);total.title=`Total semanal ${match[1]}:${match[2]}. Se encuentra bajo las ${limitText} horas.`;row.dataset.info='1';return}total.classList.add('weeklyTotalOk');total.insertAdjacentHTML('beforeend',`<span class="weeklyStatus okStatus"><span class="weeklyFace happyFace"></span><small>Horas correctas</small></span>`)})}
function enhanceFlexDays(){document.querySelectorAll('.monthlyDay').forEach(cell=>{if(!/^\s*D[ií]a\s+Flex/i.test(cell.textContent)||cell.classList.contains('info'))return;cell.classList.remove('bad');cell.classList.add('info');cell.insertAdjacentHTML('beforeend','<small>Día Flex · informativo</small>')})}
function enhanceSpecialDays(){if(!currentMonthly)return;const labels={ABSENCE:'Ausencia · informativo',UNWAIVABLE_HOLIDAY:'Feriado irrenunciable · informativo',ADDITIONAL_SUNDAY:'DA · Domingo adicional'};document.querySelectorAll('.monthlyDay').forEach(cell=>{const file=currentMonthly.files[Number(cell.dataset.file)],sheet=file?.sheets.find(x=>x.sheet===cell.dataset.sheet),row=sheet?.rows.find(x=>x.rowNumber===Number(cell.dataset.row)),day=row?.days.find(x=>x.columnNumber===Number(cell.dataset.column)),label=labels[day?.dayType];if(!label||cell.dataset.specialDay)return;cell.classList.remove('bad');cell.classList.add('info');cell.dataset.tooltip=`${label}. Estado válido sin jornada laboral; no genera error de formato ni suma horas.`;cell.insertAdjacentHTML('beforeend',`<small>${label}</small>`);cell.addEventListener('click',()=>setTimeout(()=>{$('#dayType').value=day.dayType;toggleWork()}));cell.dataset.specialDay='1'})}
function shortDuration(minutes){const hours=Math.floor(minutes/60),rest=minutes%60;return`${hours?`${hours}h`:''}${hours&&rest?' ':''}${rest?`${rest}m`:hours?'':'0m'}`}
function enhanceDailyTotals(){if(!currentMonthly)return;document.querySelectorAll('.monthlyDay').forEach(cell=>{if(cell.dataset.dailyAdded)return;const file=currentMonthly.files[Number(cell.dataset.file)],sheet=file?.sheets.find(x=>x.sheet===cell.dataset.sheet),row=sheet?.rows.find(x=>x.rowNumber===Number(cell.dataset.row)),day=row?.days.find(x=>x.columnNumber===Number(cell.dataset.column));if(!day)return;const work=day.intervals.find(x=>x.type==='WORK'),br=day.intervals.find(x=>x.type==='BREAK');if(day.correctedValue&&work&&br&&toMinutes(br.start)-toMinutes(work.start)===300)cell.classList.remove('info');const gross=day.intervals.filter(x=>x.type==='WORK').reduce((n,x)=>n+Math.max(0,endMinutes(x.start,x.end)-toMinutes(x.start)),0),breakMinutes=day.intervals.filter(x=>x.type==='BREAK').reduce((n,x)=>n+Math.max(0,endMinutes(x.start,x.end)-toMinutes(x.start)),0),worked=Math.max(0,gross-breakMinutes),badges=worked||breakMinutes?`<span class="dailyMetrics"><strong class="workMetric" title="Horas efectivas de trabajo, descontando colación">${shortDuration(worked)}</strong>${breakMinutes?`<strong class="breakMetric" title="Duración de la colación">${shortDuration(breakMinutes)}</strong>`:''}</span>`:'';cell.insertAdjacentHTML('afterbegin',badges);cell.dataset.dailyAdded='1'})}
function enhanceAutoBreakButton(){if(!currentMonthly?.results.some(x=>x.ruleCode==='MAX_WORK_BEFORE_BREAK_MINUTES')||$('#autoBreakButton'))return;const filters=$('.monthlyFilters');filters?.insertAdjacentHTML('beforeend','<button id="autoBreakButton">Corregir automáticamente colaciones</button>');$('#autoBreakButton').onclick=openAutoBreak}
function enhanceDownloadLinks(){document.querySelectorAll('a[href*="/monthly-validations/"][href$="/export"]').forEach(link=>{if(link.dataset.guardAdded)return;link.dataset.guardAdded='1';link.onclick=downloadMonthly;link.classList.toggle('downloadBlocked',!!currentMonthly?.summary?.blockingErrors);link.title=currentMonthly?.summary?.blockingErrors?'Debes corregir todos los errores bloqueantes antes de descargar.':'Descargar Excel corregido'})}
function fileCalendarMonth(file){const dates=new Set(file.sheets.flatMap(sheet=>sheet.dates)),counts=new Map;for(const date of dates){const month=date.slice(0,7);counts.set(month,(counts.get(month)??0)+1)}return[...counts].sort((a,b)=>b[1]-a[1]||b[0].localeCompare(a[0]))[0]?.[0]??''}
function calendarMonthLabel(month){if(!month)return'Mes no identificado';const[y,m]=month.split('-').map(Number),text=new Intl.DateTimeFormat('es-CL',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,1)));return text.charAt(0).toUpperCase()+text.slice(1)}
function enhanceMonthGrouping(){if(!currentMonthly||$('#previousMonths')||$('.currentMonthTitle'))return;const result=$('#monthlyResult'),sections=[...result.querySelectorAll(':scope > .monthlyFile')];if(!sections.length)return;sections.forEach((section,index)=>section.dataset.fileIndex=String(index));const months=currentMonthly.files.map(fileCalendarMonth),latest=[...months].sort().at(-1),latestSections=sections.filter(section=>months[Number(section.dataset.fileIndex)]===latest),previousSections=sections.filter(section=>months[Number(section.dataset.fileIndex)]!==latest),title=document.createElement('div');title.className='currentMonthTitle';title.innerHTML=`<span>Mes mostrado</span><strong>${calendarMonthLabel(latest)}</strong>`;result.append(title);latestSections.forEach(section=>result.append(section));if(previousSections.length){const details=document.createElement('details');details.id='previousMonths';details.className='previousMonths';const previousLabels=[...new Set(previousSections.map(section=>calendarMonthLabel(months[Number(section.dataset.fileIndex)])))];details.innerHTML=`<summary>Ver meses anteriores (${previousLabels.join(', ')})</summary>`;previousSections.forEach(section=>details.append(section));result.append(details)}}
function enhanceCalendarInfo(){if(!currentMonthly)return;const dayNames=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],allFreeSundays=new Map;for(const file of currentMonthly.files)for(const sheet of file.sheets)for(const row of sheet.rows){const employee=row.code||row.name;for(const day of row.days)if(day.dayType==='FREE'&&new Date(`${day.date}T12:00:00Z`).getUTCDay()===0){const key=`${employee}|${day.date.slice(0,7)}`,dates=allFreeSundays.get(key)??new Set;dates.add(day.date);allFreeSundays.set(key,dates)}}document.querySelectorAll('.monthlyFile').forEach(fileElement=>{const fileIndex=Number(fileElement.dataset.fileIndex),file=currentMonthly.files[fileIndex];if(!file)return;const month=fileCalendarMonth(file);fileElement.querySelectorAll('.monthlySheet').forEach((sheetElement,sheetIndex)=>{const sheet=file.sheets[sheetIndex];if(!sheet)return;const headers=sheetElement.querySelectorAll('thead th');sheet.dates.forEach((date,index)=>{const header=headers[index+5];if(header&&!header.dataset.weekdayAdded){header.textContent=`${date} · ${dayNames[new Date(`${date}T12:00:00Z`).getUTCDay()]}`;header.dataset.weekdayAdded='1'}});sheetElement.querySelectorAll('tbody .monthlyEmployeeRow').forEach((rowElement,rowIndex)=>{const row=sheet.rows[rowIndex];rowElement.dataset.code=row?.code??'';if(rowElement.querySelector('.freeSundayCount'))return;const employee=row?.code||row?.name,count=allFreeSundays.get(`${employee}|${month}`)?.size??0,nameCell=rowElement.firstElementChild;nameCell?.insertAdjacentHTML('beforeend',`<span class="freeSundayCount ${count>=2?'sundayOk':'sundayError'}" title="Solo considera domingos del mes calendario ${calendarMonthLabel(month)}">Domingos libres en ${calendarMonthLabel(month)}: ${count}</span>`)})})})}
function enhanceSundayGuide(){const list=document.querySelector('.legalGuide ul');if(list&&!list.querySelector('.rotationScopeGuide'))list.insertAdjacentHTML('beforeend','<li class="rotationScopeGuide">La rotación de horario predominante aplica únicamente a Vendedor/Vendedores y Vendedor Nocturno/Vendedores Nocturnos. No aplica a Operaciones.</li>');if(list&&!list.querySelector('.sundayGuide'))list.insertAdjacentHTML('beforeend','<li class="sundayGuide">Domingos libres: cada colaborador debe tener al menos 2 domingos marcados como Libre dentro del mes calendario. Se incluyen domingos ubicados en archivos contiguos si pertenecen al mes evaluado y se excluyen los domingos del mes siguiente.</li>')}
enhanceSundayGuide();
new MutationObserver(()=>{enhanceFlexDays();enhanceSpecialDays();enhanceDailyTotals();enhanceMonthGrouping();enhanceCalendarInfo();restoringMonthlyFilters=true;enhanceMonthlyFilters();restoringMonthlyFilters=false;restoreMonthlyFilters();enhanceWeeklyTotals();enhanceAutoBreakButton();enhanceDownloadLinks();enhanceSundayGuide()}).observe($('#monthlyResult'),{childList:true,subtree:true});
let autoBreakCandidates=[];
async function openAutoBreak(){const response=await api(`/api/v1/monthly-validations/${currentMonthly.id}/auto-correct-breaks`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),data=await response.json();autoBreakCandidates=data.candidates||[];$('#autoBreakList').innerHTML=autoBreakCandidates.length?autoBreakCandidates.map(x=>`<div class="autoBreakOption"><span><b>${escape(x.employee)} · ${escape(x.date)}</b><br><del>${escape(x.originalValue)}</del><br><strong>${escape(x.correctedValue)}</strong><br><small>Duración conservada: ${x.breakDurationMinutes} minutos</small></span></div>`).join(''):'<div class="banner ok">No existen colaciones pendientes de corrección automática.</div>';$('#applyAutoBreak').disabled=!autoBreakCandidates.length;$('#applyAutoBreak').textContent=`Corregir todas (${autoBreakCandidates.length}) y recalcular`;$('#autoBreakDialog').showModal()}
$('#closeAutoBreak').onclick=$('#cancelAutoBreak').onclick=()=>$('#autoBreakDialog').close();
$('#applyAutoBreak').onclick=async()=>{if(!autoBreakCandidates.length)return;const button=$('#applyAutoBreak');button.disabled=true;button.textContent='Corrigiendo todas y recalculando…';const response=await api(`/api/v1/monthly-validations/${currentMonthly.id}/auto-correct-breaks`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({apply:true})}),data=await response.json();renderMonthly(data);$('#autoBreakDialog').close();button.disabled=false;button.textContent='Corregir todas y recalcular'};
$('#breakStart').step=900;$('#breakEnd').step=900;
$('#save').onclick=async()=>{const type=$('#dayType').value,intervals=[];if(type==='WORK'){document.querySelectorAll('.turn').forEach((x,i)=>intervals.push({type:'WORK',start:x.querySelector('.start').value,end:x.querySelector('.end').value,position:i+1}));if($('#breakStart').value||$('#breakEnd').value)intervals.push({type:'BREAK',start:$('#breakStart').value,end:$('#breakEnd').value,position:1});if(!editingMonthly&&intervals.some(x=>!x.start||!x.end||toMinutes(x.start)%15||toMinutes(x.end)%15)){alert('Todas las horas deben estar en intervalos de 15 minutos: :00, :15, :30 o :45.');return}}if(editingMonthly){const response=await api(`/api/v1/monthly-validations/${currentMonthly.id}/cells`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...editingMonthly,dayType:type,intervals})});renderMonthly(await response.json());editingMonthly=null}else{const response=await api(`/api/v1/planning-imports/${current.id}/days/${editing.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({dayType:type,intervals,reason:$('#reason').value})});render(await response.json())}$('#editor').close()};
