import{describe,it,expect}from'vitest';import{LegalValidationEngine}from'../src/legal/engine.js';import{resolveRules}from'../src/legal/resolver.js';import type{EmployeePlanning,LegalContext,LegalRule}from'../src/legal/types.js';
const rule=(code:string,value:string,extra:Partial<LegalRule>={}):LegalRule=>({id:code+value,code,name:code,category:'LABOR_LEGAL',valid_from:'2026-04-26',severity:'ERROR',scope:'GLOBAL',parameter_type:'MINUTES',parameter_value:value,enabled:1,blocking:1,version:1,...extra});
const shift=(date:string,start='09:00',end='16:00',br?:[string,string])=>({id:date,date,dayName:'LUNES' as const,dayType:'WORK',intervals:[{type:'WORK' as const,start,end,position:1},...(br?[{type:'BREAK' as const,start:br[0],end:br[1],position:1}]:[])]});
const employee=(days:any[],extra:Partial<EmployeePlanning>={}):EmployeePlanning=>({rowId:'r1',storeId:'s1',storeName:'Local 1',employee:{id:'e1',rut:'123456785',name:'Ana',active:true,status:'ACTIVE',roleCode:'VENDEDOR'},contract:{weeklyContractMinutes:2520,splitShiftAllowed:true},days,...extra});
const context=(employees:EmployeePlanning[],rules:LegalRule[],extra:Partial<LegalContext>={}):LegalContext=>({weekStart:'2026-08-31',weekEnd:'2026-09-06',employees,rules,history:[],openingHours:[],...extra});
describe('motor de legalidades',()=>{
 it('acepta exactamente 42 horas',()=>{const e=employee(Array.from({length:6},(_,i)=>shift(`2026-09-0${i+1}`)));expect(new LegalValidationEngine().run(context([e],[rule('MAX_WEEKLY_ORDINARY_HOURS','2520')])).results.some(x=>x.ruleCode==='MAX_WEEKLY_ORDINARY_HOURS')).toBe(false)});
 it('bloquea más de 42 horas',()=>{const e=employee(Array.from({length:7},(_,i)=>shift(`2026-09-0${i+1}`)));expect(new LegalValidationEngine().run(context([e],[rule('MAX_WEEKLY_ORDINARY_HOURS','2520')])).blockingErrors).toBeGreaterThan(0)});
 it('distingue límite contractual',()=>{const e=employee([shift('2026-09-01','09:00','16:00')],{contract:{weeklyContractMinutes:300,splitShiftAllowed:true}});expect(new LegalValidationEngine().run(context([e],[])).results.find(x=>x.ruleCode==='CONTRACT_WEEKLY_HOURS')?.severity).toBe('WARNING')});
 it('acepta 10 horas diarias y rechaza más',()=>{const r=rule('MAX_DAILY_ORDINARY_HOURS','600'),ok=employee([shift('2026-09-01','08:00','18:00')]),bad=employee([shift('2026-09-01','08:00','18:01')]);expect(new LegalValidationEngine().run(context([ok],[r])).blockingErrors).toBe(0);expect(new LegalValidationEngine().run(context([bad],[r])).blockingErrors).toBe(1)});
 it('evalúa jornada dividida según contrato',()=>{const d=shift('2026-09-01');d.intervals=[{type:'WORK',start:'09:00',end:'13:00',position:1},{type:'WORK',start:'17:00',end:'21:00',position:2}];const e=employee([d],{contract:{weeklyContractMinutes:2520,splitShiftAllowed:false}});expect(new LegalValidationEngine().run(context([e],[])).results.some(x=>x.ruleCode==='SPLIT_SHIFT_ALLOWED'&&x.blocking)).toBe(true)});
 it('usa histórico para días consecutivos',()=>{const e=employee(Array.from({length:6},(_,i)=>shift(`2026-08-${31+i}`))),history=[{employeeId:'e1',date:'2026-08-30',dayType:'WORK',firstStart:'09:00',lastEnd:'16:00'}];expect(new LegalValidationEngine().run(context([e],[rule('MAX_CONSECUTIVE_WORK_DAYS','6',{parameter_type:'INTEGER'})],{history})).results.some(x=>x.ruleCode==='MAX_CONSECUTIVE_WORK_DAYS')).toBe(true)});
 it('controla descanso entre jornadas',()=>{const e=employee([shift('2026-09-01','14:00','22:00'),shift('2026-09-02','07:00','15:00')]);expect(new LegalValidationEngine().run(context([e],[rule('MIN_REST_BETWEEN_WORK_DAYS','720')])).results[0].actualValue).toBe('540')});
 it('bloquea colación iniciada después de 5 horas',()=>{const e=employee([shift('2026-09-01','11:15','19:45',['16:16','17:16'])]),r=rule('MAX_WORK_BEFORE_BREAK_MINUTES','300');const out=new LegalValidationEngine().run(context([e],[r]));expect(out.results[0].ruleCode).toBe('MAX_WORK_BEFORE_BREAK_MINUTES');expect(out.results[0].actualValue).toBe('301')});
 it('acepta colación antes de 5 horas',()=>{const e=employee([shift('2026-09-01','11:15','19:45',['15:00','16:00'])]),r=rule('MAX_WORK_BEFORE_BREAK_MINUTES','300');expect(new LegalValidationEngine().run(context([e],[r])).blockingErrors).toBe(0)});
 it('detecta hueco QF y une múltiples profesionales',()=>{const a=employee([shift('2026-09-01','08:00','14:00')],{employee:{id:'a',rut:'1',name:'A',active:true,roleCode:'QUIMICO_FARMACEUTICO'}}),b=employee([shift('2026-09-01','15:00','22:00')],{employee:{id:'b',rut:'2',name:'B',active:true,roleCode:'QUIMICO_FARMACEUTICO'}}),openingHours=[{storeId:'s1',date:'2026-09-01',start:'08:00',end:'22:00'}];const out=new LegalValidationEngine().run(context([a,b],[],{openingHours}));expect(out.results.find(x=>x.ruleCode==='QF_COVERAGE')?.message).toContain('14:00 - 15:00');b.days=[shift('2026-09-01','13:30','22:00')];expect(new LegalValidationEngine().run(context([a,b],[],{openingHours})).results.some(x=>x.ruleCode==='QF_COVERAGE')).toBe(false)});
 it('considera colación de QF como ausencia',()=>{const q=employee([shift('2026-09-01','08:00','16:00',['13:00','14:00'])],{employee:{id:'q',rut:'1',name:'Q',active:true,roleCode:'QUIMICO_FARMACEUTICO'}}),openingHours=[{storeId:'s1',date:'2026-09-01',start:'08:00',end:'16:00'}];expect(new LegalValidationEngine().run(context([q],[],{openingHours})).results[0].fromTime).toBe('13:00')});
});
describe('resolución versionada',()=>{
 it('elige regla vigente histórica o futura',()=>{const old=rule('MAX','2700',{valid_from:'2024-01-01',valid_to:'2026-04-25'}),next=rule('MAX','2520',{valid_from:'2026-04-26',version:2});expect(resolveRules([old,next],'2026-04-25').get('MAX')?.parameter_value).toBe('2700');expect(resolveRules([old,next],'2026-08-31').get('MAX')?.parameter_value).toBe('2520')});
 it('ignora deshabilitada y aplica override por empleado',()=>{const global=rule('MAX','2520'),disabled=rule('OTHER','1',{enabled:0}),personal=rule('MAX','2400',{scope:'EMPLOYEE',scope_ref_id:'e1'});const e=employee([]);const out=resolveRules([global,disabled,personal],'2026-08-31',e);expect(out.get('MAX')?.parameter_value).toBe('2400');expect(out.has('OTHER')).toBe(false)});
});
