import{dayMetrics,hhmm,minutes,type EmployeePlanning,type LegalContext,type LegalResult,type LegalRule,type LegalRuleEvaluator}from'./types.js';
const result=(r:LegalRule,e:EmployeePlanning,message:string,more:Partial<LegalResult>={}):LegalResult=>({ruleCode:r.code,severity:r.severity,blocking:!!r.blocking,employeeId:e.employee.id,storeId:e.storeId,message,...more});
export class HoursEvaluator implements LegalRuleEvaluator{
 codes=['MAX_WEEKLY_ORDINARY_HOURS','MAX_DAILY_ORDINARY_HOURS'];
 evaluate(_c:LegalContext,e:EmployeePlanning|undefined,rules:Map<string,LegalRule>):LegalResult[]{if(!e)return[];const out:LegalResult[]=[],metrics=e.days.map(d=>[d,dayMetrics(d)]as const),weekly=metrics.reduce((n,[,m])=>n+m.workedMinutes,0),wr=rules.get(this.codes[0]),dr=rules.get(this.codes[1]);if(wr&&weekly>Number(wr.parameter_value)){const limit=Number(wr.parameter_value);let accumulated=0,causing=metrics.at(-1);for(const item of metrics){accumulated+=item[1].workedMinutes;if(accumulated>limit){causing=item;break}}out.push(result(wr,e,`Jornada semanal excedida: ${hhmm(weekly)} planificadas, máximo ${hhmm(limit)}. El turno del ${causing?.[0].date} hace que el acumulado llegue a ${hhmm(accumulated)}.`,{date:causing?.[0].date,actualValue:String(weekly),expectedValue:wr.parameter_value,metadata:{accumulatedAtViolation:accumulated,excessMinutes:weekly-limit,causingDayMinutes:causing?.[1].workedMinutes}}))}if(dr)for(const[d,m]of metrics)if(m.workedMinutes>Number(dr.parameter_value))out.push(result(dr,e,`Jornada diaria excedida el ${d.date}: ${hhmm(m.workedMinutes)}.`,{date:d.date,actualValue:String(m.workedMinutes),expectedValue:dr.parameter_value}));if(e.contract?.weeklyContractMinutes!=null&&weekly>e.contract.weeklyContractMinutes)out.push({ruleCode:'CONTRACT_WEEKLY_HOURS',severity:'WARNING',blocking:false,employeeId:e.employee.id,storeId:e.storeId,actualValue:String(weekly),expectedValue:String(e.contract.weeklyContractMinutes),message:`Excede jornada contractual: ${hhmm(weekly)} / ${hhmm(e.contract.weeklyContractMinutes)}.`});return out}
}
export class EmploymentEvaluator implements LegalRuleEvaluator{
 codes=['EMPLOYMENT_PERIOD','EMPLOYEE_ACTIVE','STORE_AUTHORIZATION'];
 evaluate(c:LegalContext,e:EmployeePlanning|undefined):LegalResult[]{if(!e)return[];if(!e.employee.id)return c.employeeMasterAvailable?[{ruleCode:'EMPLOYEE_NOT_FOUND',severity:'ERROR',blocking:true,message:`No existe colaborador para RUT ${e.employee.rut}.`,storeId:e.storeId}]:[{ruleCode:'EMPLOYEE_FROM_IMPORT',severity:'INFO',blocking:false,message:`Colaborador conservado desde el Excel. No existe un maestro interno habilitado para contrastar el RUT ${e.employee.rut}.`,storeId:e.storeId,metadata:{rut:e.employee.rut}}];const out:LegalResult[]=[];if(!e.employee.active||!['ACTIVE',undefined].includes(e.employee.status))out.push({ruleCode:'EMPLOYEE_ACTIVE',severity:'ERROR',blocking:true,employeeId:e.employee.id,message:'El colaborador no está activo.'});for(const d of e.days.filter(x=>x.dayType==='WORK')){if(e.employee.hireDate&&d.date<e.employee.hireDate)out.push({ruleCode:'EMPLOYMENT_START_DATE',severity:'ERROR',blocking:true,employeeId:e.employee.id,date:d.date,message:'Trabajador aún no contratado.'});if(e.employee.terminationDate&&d.date>e.employee.terminationDate)out.push({ruleCode:'EMPLOYMENT_END_DATE',severity:'ERROR',blocking:true,employeeId:e.employee.id,date:d.date,message:'Turno posterior a la fecha de término.'})}if(!e.contract)out.push({ruleCode:'INCOMPLETE_CONTRACT',severity:'WARNING',blocking:false,employeeId:e.employee.id,message:'Información contractual incompleta; no se asume un régimen.'});return out}
}
export class SplitBreakEvaluator implements LegalRuleEvaluator{
 codes=['BREAK_REQUIRED','MAX_WORK_BEFORE_BREAK_MINUTES','SPLIT_SHIFT_ALLOWED'];
 evaluate(_c:LegalContext,e:EmployeePlanning|undefined,rules:Map<string,LegalRule>):LegalResult[]{if(!e)return[];const out:LegalResult[]=[];for(const d of e.days){const m=dayMetrics(d);if(m.work.length>1){if(e.contract?.splitShiftAllowed===false)out.push({ruleCode:'SPLIT_SHIFT_ALLOWED',severity:'ERROR',blocking:true,employeeId:e.employee.id,date:d.date,message:'Jornada dividida no permitida.'});else if(e.contract?.splitShiftAllowed==null)out.push({ruleCode:'SPLIT_SHIFT_ALLOWED',severity:'WARNING',blocking:false,employeeId:e.employee.id,date:d.date,message:'Revisar jornada dividida: contrato sin información suficiente.'})}const br=rules.get('BREAK_REQUIRED');if(br){const p=JSON.parse(br.parameter_value);if(m.presenceMinutes>p.thresholdMinutes&&m.breakMinutes<p.minMinutes)out.push(result(br,e,`Colación insuficiente o ausente el ${d.date}.`,{date:d.date,actualValue:String(m.breakMinutes),expectedValue:String(p.minMinutes)}))}const latest=rules.get('MAX_WORK_BEFORE_BREAK_MINUTES');if(latest&&m.work.length&&m.breaks.length){const elapsed=minutes(m.breaks[0].start)-minutes(m.work[0].start),maximum=Number(latest.parameter_value);if(elapsed>maximum)out.push(result(latest,e,`La colación del ${d.date} comienza después del máximo permitido desde el inicio de jornada (${hhmm(elapsed)} / ${hhmm(maximum)}).`,{date:d.date,actualValue:String(elapsed),expectedValue:latest.parameter_value}))}}return out}
}
export class RestHistoryEvaluator implements LegalRuleEvaluator{
 codes=['MIN_REST_BETWEEN_WORK_DAYS','MAX_CONSECUTIVE_WORK_DAYS'];
 evaluate(c:LegalContext,e:EmployeePlanning|undefined,rules:Map<string,LegalRule>):LegalResult[]{if(!e)return[];const historical=e.employee.id?c.history.filter(x=>x.employeeId===e.employee.id):[],out:LegalResult[]=[],days=[...historical,...e.days.map(d=>{const m=dayMetrics(d);return{employeeId:e.employee.id||e.employee.rut,date:d.date,dayType:d.dayType,firstStart:m.firstStart,lastEnd:m.lastEnd}})].sort((a,b)=>a.date.localeCompare(b.date)),rest=rules.get(this.codes[0]),cons=rules.get(this.codes[1]);let streak=0;for(let i=0;i<days.length;i++){const d=days[i];streak=d.dayType==='WORK'?streak+1:0;if(cons&&streak>Number(cons.parameter_value)&&d.date>=c.weekStart)out.push(result(cons,e,`No se permiten más de ${cons.parameter_value} días laborales consecutivos. El ${d.date} corresponde al día consecutivo ${streak}.`,{date:d.date,actualValue:String(streak),expectedValue:cons.parameter_value}));const prev=days[i-1];if(rest&&prev?.dayType==='WORK'&&d.dayType==='WORK'&&prev.lastEnd&&d.firstStart){const gap=(prev.lastEnd==='00:00'?0:1440-minutes(prev.lastEnd))+minutes(d.firstStart);if(gap<Number(rest.parameter_value))out.push(result(rest,e,`Descanso entre jornadas insuficiente: ${hhmm(gap)}.`,{date:d.date,actualValue:String(gap),expectedValue:rest.parameter_value}))}}return out}
}
function subtract(open:[number,number],coverage:[number,number][]){let gaps:[number,number][]=[open];for(const c of coverage.sort((a,b)=>a[0]-b[0]))gaps=gaps.flatMap(g=>c[1]<=g[0]||c[0]>=g[1]?[g]:[[g[0],Math.max(g[0],c[0])],[Math.min(g[1],c[1]),g[1]]].filter(x=>x[1]>x[0])as[number,number][]);return gaps}
export class QfCoverageEvaluator implements LegalRuleEvaluator{
 codes=['QF_COVERAGE'];
 evaluate(c:LegalContext):LegalResult[]{const out:LegalResult[]=[];for(const o of c.openingHours){const qfs=c.employees.filter(e=>e.storeId===o.storeId&&e.employee.roleCode==='QUIMICO_FARMACEUTICO').flatMap(e=>{const d=e.days.find(x=>x.date===o.date);if(!d)return[];const m=dayMetrics(d),work=m.work.map(x=>[minutes(x.start),minutes(x.end)]as[number,number]);for(const b of m.breaks){const bs=minutes(b.start),be=minutes(b.end);for(let i=work.length-1;i>=0;i--){const[w1,w2]=work[i];if(bs>=w1&&be<=w2)work.splice(i,1,[w1,bs],[be,w2])}}return work});for(const g of subtract([minutes(o.start),minutes(o.end)],qfs))out.push({ruleCode:'QF_COVERAGE',severity:'ERROR',blocking:true,storeId:o.storeId,date:o.date,fromTime:hhmm(g[0]),toTime:hhmm(g[1]),actualValue:'UNCOVERED',expectedValue:`${o.start}-${o.end}`,message:`Cobertura QF incompleta: ${hhmm(g[0])} - ${hhmm(g[1])}.`})}return out}
}
