import{dayMetrics,type EmployeePlanning,type HistoricalDay,type LegalContext,type LegalResult,type LegalRule,type LegalRuleEvaluator}from'./types.js';
type Pattern={weekStart:string;start?:string;end?:string};
const addDays=(date:string,days:number)=>new Date(new Date(`${date}T12:00:00Z`).getTime()+days*86400000).toISOString().slice(0,10);
const predominant=(values:(string|undefined)[])=>{const counts=new Map<string,number>();for(const value of values)if(value)counts.set(value,(counts.get(value)??0)+1);if(!counts.size)return undefined;const highest=Math.max(...counts.values()),winners=[...counts].filter(([,count])=>count===highest).map(([value])=>value);return winners.length===1?winners[0]:undefined};
const pattern=(weekStart:string,days:{dayType:string;firstStart?:string;lastEnd?:string}[]):Pattern=>({weekStart,start:predominant(days.filter(x=>x.dayType==='WORK').map(x=>x.firstStart)),end:predominant(days.filter(x=>x.dayType==='WORK').map(x=>x.lastEnd))});
const monday=(date:string)=>{const value=new Date(`${date}T12:00:00Z`),offset=(value.getUTCDay()+6)%7;value.setUTCDate(value.getUTCDate()-offset);return value.toISOString().slice(0,10)};
export class ConsecutiveWeeksScheduleRotationRule implements LegalRuleEvaluator{
 codes=['MAX_CONSECUTIVE_WEEKS_SAME_START_OR_END_TIME'];
 evaluate(context:LegalContext,employee:EmployeePlanning|undefined,rules:Map<string,LegalRule>):LegalResult[]{
  const rule=rules.get(this.codes[0]);if(!employee||!rule||!/\/\s*Vendedor(?:es)?(?:\s+Noct(?:urno(?:s)?|\.)?)?(?:\b|$)/i.test(employee.employee.workUnitId??''))return[];const parameters=JSON.parse(rule.parameter_value||'{}'),maximum=Number(parameters.maxConsecutiveWeeks??3),checkStart=parameters.checkStartTime!==false,checkEnd=parameters.checkEndTime!==false;if(maximum<1)return[];
  const identity=employee.employee.id??employee.rowId,history=context.history.filter(day=>day.employeeId===identity&&(!day.storeId||day.storeId===employee.storeId||day.storeId===employee.storeName)&&(!day.status||day.status==='VALIDATED'||day.status==='PUBLISHED')),historicalWeeks=new Map<string,HistoricalDay[]>();for(const day of history){const start=monday(day.date),days=historicalWeeks.get(start)??[];days.push(day);historicalWeeks.set(start,days)}
  const current=pattern(context.weekStart,employee.days.map(day=>{const metrics=dayMetrics(day);return{dayType:day.dayType,firstStart:metrics.firstStart,lastEnd:metrics.lastEnd}})),patterns:Pattern[]=[];for(let offset=maximum;offset>=1;offset--){const start=addDays(context.weekStart,-7*offset),days=historicalWeeks.get(start);if(!days)return[];patterns.push(pattern(start,days))}patterns.push(current);
  const weeks=patterns.map(x=>x.weekStart),results:LegalResult[]=[],currentMetrics=employee.days.filter(x=>x.dayType==='WORK').map(day=>dayMetrics(day)),same=(field:'start'|'end')=>{const previous=patterns.slice(0,-1),value=previous[0]?.[field],currentValues=currentMetrics.map(metrics=>field==='start'?metrics.firstStart:metrics.lastEnd);return!!value&&previous.every(x=>x[field]===value)&&currentValues.length>0&&currentValues.every(x=>x===value)},push=(field:'start'|'end')=>{const value=patterns[0][field]!,kind=field==='start'?'inicio':'término';results.push({ruleCode:field==='start'?'MAX_CONSECUTIVE_WEEKS_SAME_START_TIME':'MAX_CONSECUTIVE_WEEKS_SAME_END_TIME',severity:rule.severity,blocking:!!rule.blocking,employeeId:employee.employee.id,storeId:employee.storeId,date:context.weekStart,actualValue:String(maximum+1),expectedValue:String(maximum),message:`${employee.employee.name} presenta la misma hora predominante de ${kind} (${value}) durante ${maximum+1} semanas consecutivas en ${employee.storeName}. Debe modificar la hora de ${kind} de la planificación actual.`,metadata:{sourceRuleCode:rule.code,violationType:field==='start'?'SAME_START_TIME':'SAME_END_TIME',value,consecutiveWeeks:maximum+1,weeks,rowId:employee.rowId}})};
  if(checkStart&&same('start'))push('start');if(checkEnd&&same('end'))push('end');return results;
 }
}
