import ExcelJS from'exceljs';import fs from'node:fs';import path from'node:path';
import{COLUMNS,LEGACY_COLUMNS,DAYS,parseDay,normalizeRut,validRut,formatDay,type ParsedRow,type Issue}from'./domain.js';
const iso=(v:unknown)=>{if(v instanceof Date&&!isNaN(+v))return v.toISOString().slice(0,10);const s=String(v??'').trim(),m=s.match(/^(\d{2})[-\/]([0-1]\d)[-\/](\d{4})$/);if(m)return`${m[3]}-${m[2]}-${m[1]}`;const d=new Date(s);return isNaN(+d)?null:d.toISOString().slice(0,10)};
const text=(v:any):string=>v==null?'':typeof v==='object'&&'text'in v?String(v.text):typeof v==='object'&&'result'in v?String(v.result??''):String(v);
export interface ParsedWorkbook{weekStart:string;weekEnd:string;rows:ParsedRow[];issues:Issue[]}
export async function parseWorkbook(file:string):Promise<ParsedWorkbook>{
 const wb=new ExcelJS.Workbook();await wb.xlsx.readFile(file);const ws=wb.worksheets[0];if(!ws)throw new Error('El archivo no contiene hojas.');
 const grid:any[][]=[];ws.eachRow({includeEmpty:true},(r,n)=>{grid[n-1]=[];r.eachCell({includeEmpty:true},(c,i)=>grid[n-1][i-1]=text(c.value))});
 const issues:Issue[]=[],weekStart=iso(String(grid[0]?.[1]??grid[0]?.[0]??'').replace(/^SEMANA DESDE:?\s*/i,''))??'',weekEnd=iso(String(grid[1]?.[1]??grid[1]?.[0]??'').replace(/^SEMANA HASTA:?\s*/i,''))??'';
 if(!weekStart)issues.push({code:'INVALID_WEEK_START',message:'SEMANA DESDE no es válida.',severity:'ERROR'});if(!weekEnd)issues.push({code:'INVALID_WEEK_END',message:'SEMANA HASTA no es válida.',severity:'ERROR'});
 if(weekStart&&new Date(`${weekStart}T12:00:00`).getDay()!==1)issues.push({code:'WEEK_START_NOT_MONDAY',message:'SEMANA DESDE debe ser lunes.',severity:'ERROR'});if(weekEnd&&new Date(`${weekEnd}T12:00:00`).getDay()!==0)issues.push({code:'WEEK_END_NOT_SUNDAY',message:'SEMANA HASTA debe ser domingo.',severity:'ERROR'});if(weekStart&&weekEnd&&(new Date(weekEnd).getTime()-new Date(weekStart).getTime())/86400000!==6)issues.push({code:'INVALID_WEEK_RANGE',message:'La semana debe contener siete días.',severity:'ERROR'});
 const matches=(r:any[],cols:readonly string[])=>cols.every((c,i)=>String(r?.[i]??'').trim().toUpperCase()===c),headerIndex=grid.findIndex(r=>matches(r,COLUMNS)||matches(r,LEGACY_COLUMNS));
 if(headerIndex<0){issues.push({code:'MISSING_COLUMNS',message:`Encabezados obligatorios: ${COLUMNS.join(', ')}.`,severity:'ERROR'});return{weekStart,weekEnd,rows:[],issues}}
 const legacy=matches(grid[headerIndex],LEGACY_COLUMNS),nameIndex=legacy?1:0,rutIndex=legacy?2:1,dayStart=legacy?3:2;
 const rows:ParsedRow[]=grid.slice(headerIndex+1).filter(r=>r?.some(v=>String(v).trim())).map((r,i)=>{const rut=String(r[rutIndex]??''),days=Object.fromEntries(DAYS.map((d,j)=>[d,parseDay(r[j+dayStart])]))as ParsedRow['days'],rowIssues:Issue[]=[];if(!validRut(rut))rowIssues.push({code:'INVALID_RUT',message:'RUT inválido.',severity:'ERROR',row:headerIndex+i+2,column:'RUT',originalValue:rut});return{rowNumber:headerIndex+i+2,storeOriginal:legacy?String(r[0]??''):'',employeeNameOriginal:String(r[nameIndex]??''),rutOriginal:rut,rutNormalized:normalizeRut(rut),days,issues:rowIssues}});
 if(!rows.length)issues.push({code:'NO_RECORDS',message:'El archivo no contiene registros.',severity:'ERROR'});return{weekStart,weekEnd,rows,issues};
}
function makeSheet(wb:ExcelJS.Workbook,data:any[][]){
 const ws=wb.addWorksheet('Planificación',{views:[{state:'frozen',ySplit:4}]});data.forEach(r=>ws.addRow(r));ws.columns=[{width:34},{width:16},...DAYS.map(()=>({width:25}))];ws.autoFilter={from:{row:4,column:1},to:{row:4,column:9}};const head=ws.getRow(4);head.font={bold:true,color:{argb:'FFFFFFFF'}};head.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1D4ED8'}};ws.eachRow(r=>r.eachCell(c=>c.alignment={vertical:'top',wrapText:true}));ws.dataValidations.add('C5:I500',{type:'custom',allowBlank:true,showInputMessage:true,promptTitle:'Intervalos de 15 minutos',prompt:'Use únicamente minutos :00, :15, :30 o :45.',showErrorMessage:true,errorStyle:'stop',errorTitle:'Hora no permitida',error:'Las horas deben usar minutos :00, :15, :30 o :45.',formulae:['ISERROR(SEARCH(":",SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(C5,":00",""),":15",""),":30",""),":45","")))']});return ws;
}
export async function templateBuffer(){const today=new Date(),delta=(8-today.getDay())%7||7,monday=new Date(today);monday.setDate(today.getDate()+delta);const sunday=new Date(monday);sunday.setDate(monday.getDate()+6);const display=(d:Date)=>`${String(d.getDate()).padStart(2,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${d.getFullYear()}`,wb=new ExcelJS.Workbook();makeSheet(wb,[['SEMANA DESDE',display(monday)],['SEMANA HASTA',display(sunday)],[],[...COLUMNS],['COLABORADOR EJEMPLO','12.345.678-5','11:15 a 19:45\nCol 15:00 a 16:00','L','L','L','L','L','L']]);return Buffer.from(await wb.xlsx.writeBuffer())}
export async function exportBuffer(weekStart:string,weekEnd:string,rows:any[]){const data:any[][]=[['SEMANA DESDE',weekStart],['SEMANA HASTA',weekEnd],[],[...COLUMNS]];for(const r of rows)data.push([r.employee_name_original,r.rut_original,...DAYS.map(d=>formatDay(r.days[d].day_type,r.days[d].intervals))]);const wb=new ExcelJS.Workbook();makeSheet(wb,data);return Buffer.from(await wb.xlsx.writeBuffer())}
export const saveBuffer=(dir:string,name:string,b:Buffer)=>{fs.mkdirSync(dir,{recursive:true});const p=path.join(dir,name);fs.writeFileSync(p,b);return p};
