import ExcelJS from'exceljs';import{db}from'./db.js';import{parseDay,type DayName,DAYS}from'./domain.js';import{LegalValidationEngine}from'./legal/engine.js';import{dayMetrics}from'./legal/types.js';import type{EmployeePlanning,LegalContext,LegalResult}from'./legal/types.js';
type MonthlyEmployee={key:string;code:string;name:string;contract:string;store:string;workUnit:string;days:any[]};
const value=(v:any)=>v==null?'':typeof v==='object'&&'text'in v?String(v.text):String(v);
const dateIso=(v:any)=>{const s=value(v),m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:''};
const normalizeDay=(raw:any)=>{let s=value(raw).trim();if(/^libre$/i.test(s))s='L';s=s.replace(/^(Col\s+\d{2}:\d{2})\s*-\s*(\d{2}:\d{2})$/gim,'$1 a $2');return parseDay(s)};
export async function validateMonthlyFiles(files:{path:string;originalname:string}[],corrections=new Map<string,string>()){
 const rules=db.prepare('SELECT * FROM legal_rule').all()as any[],allResults:LegalResult[]=[],fileResults:any[]=[],globalRotationHistory:any[]=[];
 for(const file of files){
  const wb=new ExcelJS.Workbook();await wb.xlsx.readFile(file.path);const employees=new Map<string,MonthlyEmployee>(),weeks:any[]=[];let inferredStore='';
  for(const ws of wb.worksheets){
   const headers=Array.from({length:7},(_,i)=>dateIso(ws.getRow(10).getCell(i+6).value));if(headers.some(x=>!x)){allResults.push({ruleCode:'MONTHLY_INVALID_DATES',severity:'ERROR',blocking:true,message:`La hoja ${ws.name} no contiene siete fechas válidas.`});continue}
   inferredStore=value(ws.getCell('A5').value).replace(/^Local:\s*/i,'')||inferredStore;const weekEmployees:EmployeePlanning[]=[];
   const sheetRows:any[]=[];for(let r=11;r<=ws.rowCount;r++){const name=value(ws.getRow(r).getCell(1).value).trim(),code=value(ws.getRow(r).getCell(2).value).trim();if(!name&&!code)continue;const store=value(ws.getRow(r).getCell(4).value).trim()||inferredStore,key=`${store}|${code}`,entry=employees.get(key)??{key,code,name,contract:value(ws.getRow(r).getCell(3).value),store,workUnit:value(ws.getRow(r).getCell(5).value),days:[]};const days=headers.map((date,i)=>{const original=value(ws.getRow(r).getCell(i+6).value),corrected=corrections.get(`${file.originalname}|${ws.name}|${r}|${i+6}`),parsed=normalizeDay(corrected??original);return{id:`${ws.name}-${r}-${i}`,date,dayName:DAYS[i]as DayName,dayType:parsed.dayType,intervals:parsed.intervals,issues:parsed.issues,originalValue:original,correctedValue:corrected,rowNumber:r,columnNumber:i+6}});entry.days.push(...days);employees.set(key,entry);weekEmployees.push({rowId:key,storeName:store,employee:{rut:code,name,workUnitId:entry.workUnit},contract:{contractType:entry.contract},days});const workedMinutes=days.reduce((n,d)=>n+dayMetrics(d).workedMinutes,0),showWeeklyHours=/\/(Vendedor|Operaciones)(?:\b|$)/i.test(entry.workUnit);sheetRows.push({key,rowNumber:r,name,code,contract:entry.contract,store,workUnit:entry.workUnit,days,workedMinutes,showWeeklyHours})}
   const rotationHistory=[...globalRotationHistory,...employees.values()].flatMap((e:any)=>'employeeId'in e?[e]:e.days.filter((d:any)=>d.date<headers[0]).map((d:any)=>{const metrics=dayMetrics(d);return{employeeId:e.key,storeId:e.store,date:d.date,dayType:d.dayType,firstStart:metrics.firstStart,lastEnd:metrics.lastEnd,status:'VALIDATED'}})),context:LegalContext={weekStart:headers[0],weekEnd:headers[6],employees:weekEmployees,rules,history:rotationHistory,openingHours:[],employeeMasterAvailable:false},validation=new LegalValidationEngine().run(context),relevant=validation.results.filter(x=>x.ruleCode!=='EMPLOYEE_FROM_IMPORT'&&x.ruleCode!=='MAX_CONSECUTIVE_WORK_DAYS').filter(x=>{if(x.ruleCode!=='MAX_WEEKLY_ORDINARY_HOURS')return true;const unit=employees.get(String(x.metadata?.rowId))?.workUnit??'';return !/Vendedor\s+Noct\.?/i.test(unit)&&/\/(Vendedor|Operaciones)(?:\b|$)/i.test(unit)});allResults.push(...relevant.map(x=>({...x,metadata:{...(x.metadata||{}),file:file.originalname,sheet:ws.name}})));weeks.push({sheet:ws.name,weekStart:headers[0],weekEnd:headers[6],employees:weekEmployees.length,dates:headers,rows:sheetRows})
   const nightRule=rules.filter((x:any)=>x.code==='MAX_WEEKLY_NIGHT_SELLER_HOURS'&&x.enabled&&x.valid_from<=headers[0]&&(!x.valid_to||x.valid_to>=headers[0])).sort((a:any,b:any)=>b.version-a.version)[0];if(nightRule)for(const row of sheetRows.filter(x=>/\/\s*Vendedor\s+Noct\.?/i.test(x.workUnit))){const limit=Number(nightRule.parameter_value);if(row.workedMinutes<=limit)continue;let accumulated=0,causing=row.days.at(-1);for(const day of row.days){accumulated+=dayMetrics(day).workedMinutes;if(accumulated>limit){causing=day;break}}allResults.push({ruleCode:nightRule.code,severity:nightRule.severity,blocking:!!nightRule.blocking,date:causing.date,actualValue:String(row.workedMinutes),expectedValue:nightRule.parameter_value,message:`${row.name}: jornada nocturna semanal de ${Math.floor(row.workedMinutes/60)}:${String(row.workedMinutes%60).padStart(2,'0')}; máximo permitido 40:00. El turno del ${causing.date} hace superar el límite.`,metadata:{file:file.originalname,sheet:ws.name,rowId:row.key,rut:row.code,accumulatedAtViolation:accumulated}})}
  }
  const maxRule=rules.filter((x:any)=>x.code==='MAX_CONSECUTIVE_WORK_DAYS'&&x.enabled).sort((a:any,b:any)=>b.version-a.version)[0];if(maxRule)for(const e of employees.values()){let streak=0;for(const d of e.days.sort((a,b)=>a.date.localeCompare(b.date))){streak=d.dayType==='WORK'?streak+1:0;if(streak>Number(maxRule.parameter_value))allResults.push({ruleCode:maxRule.code,severity:maxRule.severity,blocking:!!maxRule.blocking,date:d.date,actualValue:String(streak),expectedValue:maxRule.parameter_value,message:`No se permiten más de ${maxRule.parameter_value} días laborales consecutivos. ${e.name} alcanza ${streak} días el ${d.date}.`,metadata:{file:file.originalname,rowId:e.key,rut:e.code}})}}
  for(const e of employees.values())for(const d of e.days)for(const issue of d.issues)allResults.push({ruleCode:issue.code,severity:issue.severity==='WARNING'?'WARNING':'ERROR',blocking:issue.severity!=='WARNING',date:d.date,message:`${e.name}: ${issue.message}`,metadata:{file:file.originalname,rowId:e.key,rut:e.code,originalValue:d.originalValue}});
  fileResults.push({filename:file.originalname,store:inferredStore,sheets:weeks,employees:[...employees.values()].map(e=>({key:e.key,code:e.code,name:e.name,contract:e.contract,store:e.store,workUnit:e.workUnit,days:e.days.length}))});for(const e of employees.values())for(const d of e.days){const metrics=dayMetrics(d);globalRotationHistory.push({employeeId:e.key,storeId:e.store,date:d.date,dayType:d.dayType,firstStart:metrics.firstStart,lastEnd:metrics.lastEnd,status:'VALIDATED'})}
 }
 const unique=[...new Map(allResults.map(x=>[`${x.ruleCode}|${x.date}|${x.metadata?.file}|${x.metadata?.sheet}|${x.metadata?.rowId??x.metadata?.rut}|${x.message}`,x])).values()];return{files:fileResults,results:unique,summary:{files:files.length,stores:new Set(fileResults.map(x=>x.store)).size,employees:new Set(fileResults.flatMap(x=>x.employees.map((e:any)=>`${e.store}|${e.code}`))).size,errors:unique.filter(x=>x.severity==='ERROR').length,warnings:unique.filter(x=>x.severity==='WARNING').length,blockingErrors:unique.filter(x=>x.blocking).length}};
}
