// @ts-nocheck -- Express route adapters are dynamically shaped; domain and legal engine remain strict.
import express from 'express'; import multer from 'multer'; import fs from 'node:fs'; import path from 'node:path';
import { db,id,audit } from './db.js'; import { parseWorkbook,templateBuffer,exportBuffer,saveBuffer } from './excel.js'; import { DAYS,parseDay,formatDay,validRut } from './domain.js';
import { latestValidation,runLegalValidation } from './legal/service.js';
import { validateMonthlyFiles } from './monthly.js';
const app=express(),root=process.cwd(),uploadDir=path.join(root,'uploads');fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:10*1024*1024},fileFilter:(_r,f,cb)=>cb(null,/\.xlsx$/i.test(f.originalname))}); app.use(express.json()); app.use(express.static(path.join(root,'public')));
const auth=(req:any,res:any,next:any)=>{req.user=req.header('x-user')||'usuario.local';req.role=req.header('x-role')||'ADMIN';next()}; app.use('/api',auth);
const fail=(res:any,status:number,code:string,message:string,details={})=>res.status(status).json({code,message,details});
app.post('/api/v1/monthly-validations/:id/auto-correct-breaks',async(req:any,res)=>{
 const batch=db.prepare('SELECT * FROM monthly_validation_batch WHERE id=?').get(req.params.id)as any;
 if(!batch)return fail(res,404,'NOT_FOUND','Validación mensual no encontrada.');
 const current=JSON.parse(batch.result_json),files=db.prepare('SELECT * FROM monthly_validation_file WHERE batch_id=? ORDER BY rowid').all(batch.id)as any[];
 const unique=new Map<string,any>();
 for(let fileIndex=0;fileIndex<current.files.length;fileIndex++)for(const sheet of current.files[fileIndex].sheets)for(const row of sheet.rows)for(const day of row.days){
   const work=day.intervals.find((x:any)=>x.type==='WORK'),br=day.intervals.find((x:any)=>x.type==='BREAK');if(!work||!br)continue;
   const tm=(t:string)=>Number(t.slice(0,2))*60+Number(t.slice(3)),workStart=tm(work.start),rawBreakStart=tm(br.start),elapsed=rawBreakStart<workStart?rawBreakStart+1440-workStart:rawBreakStart-workStart;if(elapsed<=300)continue;const rawBreakEnd=tm(br.end),breakMinutes=(rawBreakEnd<=rawBreakStart?rawBreakEnd+1440:rawBreakEnd)-rawBreakStart,breakStart=workStart+300,toTime=(n:number)=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
   const intervals=day.intervals.map((x:any)=>x.type==='BREAK'?{...x,start:toTime(breakStart),end:toTime(breakStart+breakMinutes)}:x),correctedValue=formatDay('WORK',intervals),candidateId=`${fileIndex}|${sheet.sheet}|${row.rowNumber}|${day.columnNumber}`;
   if(correctedValue!==(day.correctedValue??day.originalValue))unique.set(candidateId,{id:candidateId,fileIndex,sheetName:sheet.sheet,rowNumber:row.rowNumber,columnNumber:day.columnNumber,employee:row.name,date:day.date,originalValue:day.originalValue,correctedValue,breakDurationMinutes:breakMinutes});
  }
 const candidates=[...unique.values()];if(!req.body?.apply)return res.json({candidates});
 const targets=candidates,insert=db.prepare('INSERT INTO monthly_correction VALUES(?,?,?,?,?,?,?,?,?,?)');
 db.exec('BEGIN');try{for(const c of targets)insert.run(id(),batch.id,c.fileIndex,c.sheetName,c.rowNumber,c.columnNumber,c.originalValue,c.correctedValue,req.user,new Date().toISOString());db.exec('COMMIT')}catch(error){db.exec('ROLLBACK');throw error}
 const corrections=db.prepare('SELECT * FROM monthly_correction WHERE batch_id=? ORDER BY rowid').all(batch.id)as any[],map=new Map<string,string>();for(const x of corrections)map.set(`${files[x.file_index].original_filename}|${x.sheet_name}|${x.row_number}|${x.column_number}`,x.corrected_value);
 const result=await validateMonthlyFiles(files.map(x=>({path:x.original_file_path,originalname:x.original_filename})),map),status=result.summary.blockingErrors?'CON_ERRORES':'VALIDADA';db.prepare('UPDATE monthly_validation_batch SET status=?,error_count=?,warning_count=?,result_json=? WHERE id=?').run(status,result.summary.errors,result.summary.warnings,JSON.stringify(result),batch.id);audit(null,'MONTHLY_AUTO_BREAK_CORRECTION',req.user,{batchId:batch.id,corrected:targets.length});res.json({id:batch.id,status,correctedCount:targets.length,...result});
});
app.get('/api/v1/monthly-validations/:id/files/:fileIndex/export',async(req:any,res)=>{
 const batch=db.prepare('SELECT * FROM monthly_validation_batch WHERE id=?').get(req.params.id)as any;if(!batch)return fail(res,404,'NOT_FOUND','Validación mensual no encontrada.');
 const current=JSON.parse(batch.result_json);if(current.summary.blockingErrors>0)return fail(res,409,'EXPORT_WITH_ERRORS',`No se puede descargar el Excel corregido: todavía quedan ${current.summary.blockingErrors} error(es) bloqueantes por corregir.`);
 const files=db.prepare('SELECT * FROM monthly_validation_file WHERE batch_id=? ORDER BY rowid').all(batch.id)as any[],fileIndex=Number(req.params.fileIndex),target=files[fileIndex];if(!target)return fail(res,404,'FILE_NOT_FOUND','Archivo mensual no encontrado.');
 const ExcelJS=(await import('exceljs')).default,wb=new ExcelJS.Workbook();await wb.xlsx.readFile(target.original_file_path);
 const corrections=db.prepare('SELECT * FROM monthly_correction WHERE batch_id=? AND file_index=? ORDER BY rowid').all(batch.id,fileIndex)as any[];for(const correction of corrections){const ws=wb.getWorksheet(correction.sheet_name);if(ws)ws.getRow(correction.row_number).getCell(correction.column_number).value=correction.corrected_value}
 const fileData=current.files[fileIndex],clock=(time:string)=>Number(time.slice(0,2))*60+Number(time.slice(3)),elapsed=(start:string,end:string)=>{const a=clock(start),b=clock(end);return(b<=a?b+1440:b)-a},label=(minutes:number)=>`${Math.floor(minutes/60)}h${minutes%60?` ${minutes%60}m`:''}`;
 for(const sheetData of fileData.sheets){const ws=wb.getWorksheet(sheetData.sheet);if(!ws)continue;const totalColumn=Math.max(...sheetData.rows.flatMap((row:any)=>row.days.map((day:any)=>day.columnNumber)))+1;ws.getRow(10).getCell(totalColumn).value='Total horas de trabajo';ws.getRow(10).getCell(totalColumn).font={bold:true};ws.getColumn(totalColumn).width=22;for(const row of sheetData.rows){for(const day of row.days){const work=day.intervals.filter((x:any)=>x.type==='WORK').reduce((sum:number,x:any)=>sum+elapsed(x.start,x.end),0),breakMinutes=day.intervals.filter((x:any)=>x.type==='BREAK').reduce((sum:number,x:any)=>sum+elapsed(x.start,x.end),0),effective=Math.max(0,work-breakMinutes);ws.getRow(row.rowNumber).getCell(day.columnNumber).note=`Jornada laboral efectiva: ${label(effective)}\nTiempo de colación: ${label(breakMinutes)}`}const total=ws.getRow(row.rowNumber).getCell(totalColumn);total.value=row.workedMinutes/1440;total.numFmt='[h]:mm';total.font={bold:true}}
 }
 const buffer=Buffer.from(await wb.xlsx.writeBuffer());res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment(target.original_filename.replace(/\.xlsx$/i,'_CORREGIDO.xlsx')).send(buffer);
});
function detail(importId:string){const imp=db.prepare('SELECT * FROM planning_import WHERE id=?').get(importId) as any;if(!imp)return null;const rows=db.prepare('SELECT * FROM planning_import_row WHERE import_id=? ORDER BY row_number').all(importId) as any[];for(const r of rows){r.days={};const ds=db.prepare('SELECT * FROM planning_import_day WHERE import_row_id=? ORDER BY date').all(r.id) as any[];for(const d of ds){d.intervals=db.prepare('SELECT interval_type as type,start_time as start,end_time as end,position FROM planning_import_interval WHERE planning_import_day_id=? ORDER BY position').all(d.id);d.issues=db.prepare('SELECT * FROM planning_import_issue WHERE day_id=? AND resolved=0').all(d.id);r.days[d.day_of_week]=d}r.issues=db.prepare('SELECT * FROM planning_import_issue WHERE row_id=? AND day_id IS NULL AND resolved=0').all(r.id)}imp.rows=rows;imp.issues=db.prepare('SELECT * FROM planning_import_issue WHERE import_id=? AND resolved=0').all(importId);return imp}
app.get('/api/v1/planning-template',async(_q,res)=>{audit(null,'DOWNLOAD','usuario.local',{template:true});res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment('Plantilla_Planificacion_Semanal.xlsx').send(await templateBuffer())});
app.post('/api/v1/planning-imports/upload',upload.single('file'),async(req:any,res)=>{if(!req.file)return fail(res,400,'INVALID_FILE','Debe seleccionar un archivo .xlsx.');try{const p=await parseWorkbook(req.file.path),importId=id(),now=new Date().toISOString();db.prepare('INSERT INTO planning_import VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(importId,req.file.originalname,p.weekStart,p.weekEnd,req.user,now,'PARSED',p.rows.length,0,0,0,req.file.path);for(const issue of p.issues)db.prepare('INSERT INTO planning_import_issue(id,import_id,code,message,severity,column_name,original_value) VALUES(?,?,?,?,?,?,?)').run(id(),importId,issue.code,issue.message,issue.severity,issue.column??null,issue.originalValue??null);for(const r of p.rows){const rid=id();db.prepare('INSERT INTO planning_import_row(id,import_id,row_number,store_original,employee_name_original,rut_original,rut_normalized,status) VALUES(?,?,?,?,?,?,?,?)').run(rid,importId,r.rowNumber,r.storeOriginal,r.employeeNameOriginal,r.rutOriginal,r.rutNormalized,'PENDING');for(const issue of r.issues)db.prepare('INSERT INTO planning_import_issue(id,import_id,row_id,code,message,severity,column_name,original_value) VALUES(?,?,?,?,?,?,?,?)').run(id(),importId,rid,issue.code,issue.message,issue.severity,issue.column??null,issue.originalValue??null);DAYS.forEach((day,n)=>{const d=r.days[day],did=id(),date=p.weekStart?new Date(new Date(`${p.weekStart}T12:00:00`).getTime()+n*86400000).toISOString().slice(0,10):'';db.prepare('INSERT INTO planning_import_day(id,import_row_id,date,day_of_week,original_value,day_type,status) VALUES(?,?,?,?,?,?,?)').run(did,rid,date,day,d.originalValue,d.dayType,d.issues.length?'ERROR':'OK');for(const x of d.intervals)db.prepare('INSERT INTO planning_import_interval VALUES(?,?,?,?,?,?)').run(id(),did,x.type,x.start,x.end,x.position);for(const issue of d.issues)db.prepare('INSERT INTO planning_import_issue(id,import_id,row_id,day_id,code,message,severity,column_name,original_value) VALUES(?,?,?,?,?,?,?,?,?)').run(id(),importId,rid,did,issue.code,issue.message,issue.severity,day,d.originalValue)})}audit(importId,'UPLOAD',req.user,{filename:req.file.originalname});res.status(201).json(detail(importId))}catch(e:any){fs.unlink(req.file.path,()=>{});return fail(res,422,'INVALID_EXCEL',e.message)}});
app.post('/api/v1/planning-imports/:id/confirm',(req:any,res)=>{const imp=detail(req.params.id);if(!imp)return fail(res,404,'NOT_FOUND','Importación no encontrada.');db.prepare("UPDATE planning_import SET status='READY_FOR_REVIEW' WHERE id=?").run(req.params.id);audit(req.params.id,'IMPORT',req.user);const response=detail(req.params.id);(response as any).legalValidation=runLegalValidation(req.params.id,req.user,true);res.json(response)});
app.get('/api/v1/planning-imports/:id',(req,res)=>{const d=detail(req.params.id);return d?res.json(d):fail(res,404,'NOT_FOUND','Importación no encontrada.')});
app.get('/api/v1/planning-imports/:id/issues',(req,res)=>res.json(db.prepare('SELECT * FROM planning_import_issue WHERE import_id=? AND resolved=0').all(req.params.id)));
app.post('/api/v1/planning-imports/:id/legal-validation',(req:any,res)=>{try{res.json(runLegalValidation(req.params.id,req.user,true))}catch(e:any){fail(res,404,'LEGAL_VALIDATION_FAILED',e.message)}});
app.get('/api/v1/planning-imports/:id/legal-validation',(req,res)=>{const x=latestValidation(req.params.id);return x?res.json(x):fail(res,404,'NOT_FOUND','Aún no existe una validación legal.')});
app.get('/api/v1/planning-imports/:id/employees/:employeeId/legal-validation',(req,res)=>{const run=latestValidation(req.params.id);if(!run)return fail(res,404,'NOT_FOUND','Aún no existe una validación legal.');res.json({...run,results:run.results.filter((x:any)=>x.employee_id===req.params.employeeId)})});
app.post('/api/v1/planning-imports/:id/corrections/simulate',(req:any,res)=>{try{const before=runLegalValidation(req.params.id,req.user,false),parsed=parseDay(formatDay(req.body.dayType,req.body.intervals??[])),overrides=new Map([[req.body.dayId,{dayType:parsed.dayType,intervals:parsed.intervals}]]),after=runLegalValidation(req.params.id,req.user,false,overrides);res.json({before,after})}catch(e:any){fail(res,422,'SIMULATION_FAILED',e.message)}});
app.get('/api/v1/legal-rules',(_req,res)=>res.json(db.prepare('SELECT * FROM legal_rule ORDER BY code,valid_from,version').all()));
app.post('/api/v1/monthly-validations/upload',upload.array('files',20),async(req:any,res)=>{const files=req.files as Express.Multer.File[];if(!files?.length)return fail(res,400,'FILES_REQUIRED','Seleccione al menos un archivo .xlsx.');try{const result=await validateMonthlyFiles(files),batchId=id(),now=new Date().toISOString(),status=result.summary.blockingErrors?'CON_ERRORES':'VALIDADA';db.prepare('INSERT INTO monthly_validation_batch VALUES(?,?,?,?,?,?,?,?,?,?)').run(batchId,req.user,now,status,result.summary.files,result.summary.stores,result.summary.employees,result.summary.errors,result.summary.warnings,JSON.stringify(result));for(const f of files){const parsed=result.files.find((x:any)=>x.filename===f.originalname);db.prepare('INSERT INTO monthly_validation_file VALUES(?,?,?,?,?)').run(id(),batchId,f.originalname,f.path,parsed?.store??'')}audit(null,'MONTHLY_VALIDATION',req.user,{batchId,...result.summary});res.status(201).json({id:batchId,status,...result})}catch(e:any){fail(res,422,'MONTHLY_VALIDATION_FAILED',e.message)}});
app.get('/api/v1/monthly-validations/:id',(req,res)=>{const batch=db.prepare('SELECT * FROM monthly_validation_batch WHERE id=?').get(req.params.id)as any;if(!batch)return fail(res,404,'NOT_FOUND','Validación mensual no encontrada.');res.json({id:batch.id,status:batch.status,...JSON.parse(batch.result_json)})});
app.put('/api/v1/monthly-validations/:id/cells',(req:any,res)=>{const batch=db.prepare('SELECT * FROM monthly_validation_batch WHERE id=?').get(req.params.id)as any;if(!batch)return fail(res,404,'NOT_FOUND','Validación mensual no encontrada.');const files=db.prepare('SELECT * FROM monthly_validation_file WHERE batch_id=? ORDER BY rowid').all(batch.id)as any[],target=files[req.body.fileIndex];if(!target)return fail(res,404,'FILE_NOT_FOUND','Archivo mensual no encontrado.');const current=JSON.parse(batch.result_json),day=current.files[req.body.fileIndex]?.sheets?.find((x:any)=>x.sheet===req.body.sheetName)?.rows?.find((x:any)=>x.rowNumber===req.body.rowNumber)?.days?.find((x:any)=>x.columnNumber===req.body.columnNumber);if(!day)return fail(res,404,'CELL_NOT_FOUND','Celda mensual no encontrada.');const corrected=formatDay(req.body.dayType,req.body.intervals??[]);db.prepare('INSERT INTO monthly_correction VALUES(?,?,?,?,?,?,?,?,?,?)').run(id(),batch.id,req.body.fileIndex,req.body.sheetName,req.body.rowNumber,req.body.columnNumber,day.originalValue,corrected,req.user,new Date().toISOString());const corrections=db.prepare('SELECT * FROM monthly_correction WHERE batch_id=? ORDER BY changed_at').all(batch.id)as any[],map=new Map<string,string>();for(const x of corrections)map.set(`${files[x.file_index].original_filename}|${x.sheet_name}|${x.row_number}|${x.column_number}`,x.corrected_value);validateMonthlyFiles(files.map(x=>({path:x.original_file_path,originalname:x.original_filename})),map).then(result=>{const status=result.summary.blockingErrors?'CON_ERRORES':'VALIDADA';db.prepare('UPDATE monthly_validation_batch SET status=?,error_count=?,warning_count=?,result_json=? WHERE id=?').run(status,result.summary.errors,result.summary.warnings,JSON.stringify(result),batch.id);audit(null,'MONTHLY_CORRECTION',req.user,{batchId:batch.id,sheet:req.body.sheetName,row:req.body.rowNumber,column:req.body.columnNumber});res.json({id:batch.id,status,...result})}).catch((e:any)=>fail(res,422,'MONTHLY_CORRECTION_FAILED',e.message))});
app.post('/api/v1/monthly-validations/:id/auto-correct-breaks',async(req:any,res)=>{const batch=db.prepare('SELECT * FROM monthly_validation_batch WHERE id=?').get(req.params.id)as any;if(!batch)return fail(res,404,'NOT_FOUND','Validación mensual no encontrada.');const current=JSON.parse(batch.result_json),files=db.prepare('SELECT * FROM monthly_validation_file WHERE batch_id=? ORDER BY rowid').all(batch.id)as any[],candidates:any[]=[];for(const issue of current.results.filter((x:any)=>x.ruleCode==='MAX_WORK_BEFORE_BREAK_MINUTES')){const fileIndex=current.files.findIndex((x:any)=>x.filename===issue.metadata?.file),file=current.files[fileIndex];for(const sheet of file?.sheets??[])for(const row of sheet.rows.filter((x:any)=>x.key===issue.metadata?.rowId))for(const day of row.days.filter((x:any)=>x.date===issue.date)){const work=day.intervals.find((x:any)=>x.type==='WORK'),br=day.intervals.find((x:any)=>x.type==='BREAK');if(!work||!br)continue;const tm=(t:string)=>Number(t.slice(0,2))*60+Number(t.slice(3)),duration=(br.end==='00:00'&&br.start!=='00:00'?1440:tm(br.end))-tm(br.start),start=tm(work.start)+300,end=start+duration,toTime=(n:number)=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`,intervals=day.intervals.map((x:any)=>x.type==='BREAK'?{...x,start:toTime(start),end:toTime(end)}:x),correctedValue=formatDay('WORK',intervals),candidateId=`${fileIndex}|${sheet.sheet}|${row.rowNumber}|${day.columnNumber}`;candidates.push({id:candidateId,fileIndex,sheetName:sheet.sheet,rowNumber:row.rowNumber,columnNumber:day.columnNumber,employee:row.name,date:day.date,originalValue:day.correctedValue??day.originalValue,correctedValue,intervals,breakDurationMinutes:duration})}}if(!req.body?.apply)return res.json({candidates});const selected=new Set<string>(req.body.selected??candidates.map(x=>x.id));for(const c of candidates.filter(x=>selected.has(x.id)))db.prepare('INSERT INTO monthly_correction VALUES(?,?,?,?,?,?,?,?,?,?)').run(id(),batch.id,c.fileIndex,c.sheetName,c.rowNumber,c.columnNumber,c.originalValue,c.correctedValue,req.user,new Date().toISOString());const corrections=db.prepare('SELECT * FROM monthly_correction WHERE batch_id=? ORDER BY changed_at').all(batch.id)as any[],map=new Map<string,string>();for(const x of corrections)map.set(`${files[x.file_index].original_filename}|${x.sheet_name}|${x.row_number}|${x.column_number}`,x.corrected_value);const result=await validateMonthlyFiles(files.map(x=>({path:x.original_file_path,originalname:x.original_filename})),map),status=result.summary.blockingErrors?'CON_ERRORES':'VALIDADA';db.prepare('UPDATE monthly_validation_batch SET status=?,error_count=?,warning_count=?,result_json=? WHERE id=?').run(status,result.summary.errors,result.summary.warnings,JSON.stringify(result),batch.id);audit(null,'MONTHLY_AUTO_BREAK_CORRECTION',req.user,{batchId:batch.id,corrected:selected.size});res.json({id:batch.id,status,...result})});
app.get('/api/v1/monthly-validations/:id/files/:fileIndex/export',async(req:any,res)=>{const files=db.prepare('SELECT * FROM monthly_validation_file WHERE batch_id=? ORDER BY rowid').all(req.params.id)as any[],target=files[Number(req.params.fileIndex)];if(!target)return fail(res,404,'FILE_NOT_FOUND','Archivo mensual no encontrado.');const wb=new (await import('exceljs')).default.Workbook();await wb.xlsx.readFile(target.original_file_path);const corrections=db.prepare('SELECT * FROM monthly_correction WHERE batch_id=? AND file_index=? ORDER BY changed_at').all(req.params.id,Number(req.params.fileIndex))as any[];for(const x of corrections){const ws=wb.getWorksheet(x.sheet_name);if(ws)ws.getRow(x.row_number).getCell(x.column_number).value=x.corrected_value}const buffer=Buffer.from(await wb.xlsx.writeBuffer());res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment(target.original_filename.replace(/\.xlsx$/i,'_CORREGIDO.xlsx')).send(buffer)});
app.post('/api/v1/legal-rules',(req:any,res)=>{const x=req.body,now=new Date().toISOString(),rid=id();db.prepare('INSERT INTO legal_rule VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(rid,x.code,x.name,x.description,x.category,x.country??'CL',x.validFrom,x.validTo??null,x.severity,x.scope,x.scopeRefId??null,x.parameterType,x.parameterValue,x.enabled===false?0:1,x.blocking?1:0,x.sourceReference??null,x.version??1,now,now,req.user,req.user);res.status(201).json(db.prepare('SELECT * FROM legal_rule WHERE id=?').get(rid))});
app.put('/api/v1/legal-rules/:id',(req:any,res)=>{const previous=db.prepare('SELECT * FROM legal_rule WHERE id=?').get(req.params.id)as any;if(!previous)return fail(res,404,'NOT_FOUND','Regla no encontrada.');const used=db.prepare("SELECT COUNT(*) n FROM legal_validation_run WHERE rule_snapshot LIKE ?").get(`%${previous.id}%`)as any;if(used.n)return fail(res,409,'IMMUTABLE_RULE','La regla ya fue utilizada; cree una nueva versión.');const x=req.body;db.prepare('UPDATE legal_rule SET name=?,description=?,valid_to=?,severity=?,parameter_value=?,enabled=?,blocking=?,source_reference=?,updated_at=?,updated_by=? WHERE id=?').run(x.name??previous.name,x.description??previous.description,x.validTo??previous.valid_to,x.severity??previous.severity,x.parameterValue??previous.parameter_value,x.enabled??previous.enabled,x.blocking??previous.blocking,x.sourceReference??previous.source_reference,new Date().toISOString(),req.user,previous.id);res.json(db.prepare('SELECT * FROM legal_rule WHERE id=?').get(previous.id))});
app.put('/api/v1/planning-imports/:id/days/:dayId',(req:any,res)=>{const old=db.prepare('SELECT d.*,r.id row_id,r.employee_id FROM planning_import_day d JOIN planning_import_row r ON r.id=d.import_row_id WHERE d.id=? AND r.import_id=?').get(req.params.dayId,req.params.id) as any;if(!old)return fail(res,404,'NOT_FOUND','Día no encontrado.');const value=formatDay(req.body.dayType,req.body.intervals??[]),parsed=parseDay(value);db.prepare('UPDATE planning_import_issue SET resolved=1 WHERE day_id=?').run(old.id);db.prepare('DELETE FROM planning_import_interval WHERE planning_import_day_id=?').run(old.id);db.prepare('UPDATE planning_import_day SET corrected_value=?,day_type=?,status=? WHERE id=?').run(value,parsed.dayType,parsed.issues.length?'ERROR':'OK',old.id);for(const x of parsed.intervals)db.prepare('INSERT INTO planning_import_interval VALUES(?,?,?,?,?,?)').run(id(),old.id,x.type,x.start,x.end,x.position);for(const x of parsed.issues)db.prepare('INSERT INTO planning_import_issue(id,import_id,row_id,day_id,code,message,severity,column_name,original_value) VALUES(?,?,?,?,?,?,?,?,?)').run(id(),req.params.id,old.row_id,old.id,x.code,x.message,x.severity,old.day_of_week,value);db.prepare('INSERT INTO planning_correction VALUES(?,?,?,?,?,?,?,?,?,?)').run(id(),req.params.id,old.row_id,old.employee_id,old.date,old.original_value,value,req.user,new Date().toISOString(),req.body.reason??null);db.prepare("UPDATE planning_import SET status='CORRECTED' WHERE id=?").run(req.params.id);audit(req.params.id,'CORRECTION_APPLIED',req.user,{dayId:old.id});const legal=runLegalValidation(req.params.id,req.user,true);res.json({...detail(req.params.id),legalValidation:legal})});
app.post('/api/v1/planning-imports/:id/validate',(req:any,res)=>{const imp=detail(req.params.id);if(!imp)return fail(res,404,'NOT_FOUND','Importación no encontrada.');const structuralErrors=(imp.issues as any[]).filter(x=>x.severity==='ERROR').length,legal=runLegalValidation(req.params.id,req.user,true),errors=structuralErrors+legal.blockingErrors,warnings=(imp.issues as any[]).filter(x=>x.severity==='WARNING').length+legal.warnings,corrected=db.prepare('SELECT COUNT(*) n FROM planning_correction WHERE import_batch_id=?').get(req.params.id) as any,status=errors?'WITH_ERRORS':corrected.n?'VALIDATED_AFTER_CORRECTION':'VALIDATED';db.prepare('UPDATE planning_import SET status=?,error_rows=?,warning_rows=?,valid_rows=? WHERE id=?').run(status,errors,warnings,errors?0:imp.total_rows,req.params.id);db.prepare('INSERT INTO planning_validation VALUES(?,?,?,?,?,?,?)').run(id(),req.params.id,req.user,new Date().toISOString(),status,errors,warnings);audit(req.params.id,corrected.n?'LEGAL_REVALIDATION':'VALIDATE',req.user,{errors,warnings,ruleSetVersion:legal.ruleSetVersion});const response=detail(req.params.id);(response as any).legalValidation=legal;res.status(errors?422:200).json(response)});
app.post('/api/v1/planning-imports/:id/export',async(req:any,res)=>{const imp=detail(req.params.id);if(!imp)return fail(res,404,'NOT_FOUND','Importación no encontrada.');if(!['VALIDATED','VALIDATED_AFTER_CORRECTION'].includes(imp.status))return fail(res,409,'NOT_VALIDATED','La planificación debe validarse sin errores antes de exportar.');const corrected=db.prepare('SELECT COUNT(*) n FROM planning_correction WHERE import_batch_id=?').get(req.params.id) as any;const suffix=corrected.n?'CORREGIDA':'VALIDADA',filename=`Planificacion_${imp.week_start}_${imp.week_end}_${suffix}.xlsx`,eid=id(),file=saveBuffer(path.join(root,'exports'),`${eid}.xlsx`,await exportBuffer(imp.week_start,imp.week_end,imp.rows));db.prepare('INSERT INTO planning_export VALUES(?,?,?,?,?,?,?)').run(eid,imp.id,file,filename,req.user,new Date().toISOString(),corrected.n?2:1);audit(imp.id,'EXPORT',req.user,{exportId:eid});res.status(201).json({id:eid,filename,url:`/api/v1/planning-imports/${imp.id}/exports/${eid}`})});
app.get('/api/v1/planning-imports/:id/exports/:exportId',(req:any,res)=>{const x=db.prepare('SELECT * FROM planning_export WHERE id=? AND import_id=?').get(req.params.exportId,req.params.id) as any;if(!x)return fail(res,404,'NOT_FOUND','Exportación no encontrada.');audit(req.params.id,'DOWNLOAD',req.user,{exportId:x.id});res.download(x.file_path,x.filename)});
app.use((e:any,_q:any,res:any,_n:any)=>fail(res,e instanceof multer.MulterError?400:500,'REQUEST_ERROR',e.message));
const port=Number(process.env.PORT||3100);if(process.env.NODE_ENV!=='test')app.listen(port,()=>console.log(`Planificador disponible en http://localhost:${port}`));export default app;
